<?php

namespace App\Console\Commands;

use App\Models\DataSource;
use App\Models\Period;
use App\Models\ReportUpload;
use Illuminate\Console\Command;
use Illuminate\Support\Collection;

class DebugSourcesCommand extends Command
{
    protected $signature   = 'reportes:debug-sources {periodId : ID del periodo}';
    protected $description = 'Diagnóstico completo de fuentes para un periodo: tipo, cobertura, can_receive_uploads, uploads por fuente, fuentes faltantes.';

    public function handle(): int
    {
        $periodId = (int) $this->argument('periodId');
        $period   = Period::find($periodId);

        if (!$period) {
            $this->error("Periodo #{$periodId} no encontrado.");
            return self::FAILURE;
        }

        $allPeriods = Period::query()->get();

        $this->line('');
        $this->info("══════════════════════════════════════════════════════════");
        $this->info("  DEBUG SOURCES — Periodo #{$periodId}: {$period->label}");
        $this->info("══════════════════════════════════════════════════════════");
        $this->line('');

        // ── Información del periodo ────────────────────────────────────
        $this->info('── Periodo ──');
        $this->line("  ID             : {$period->id}");
        $this->line("  Código         : {$period->code}");
        $this->line("  Tipo           : {$period->type}");
        $this->line("  Año/Mes        : {$period->year}-{$period->month}");
        $this->line("  Fechas         : " . optional($period->start_date)->format('d/m/Y') . " → " . optional($period->end_date)->format('d/m/Y'));
        $this->line("  is_closed      : " . ($period->is_closed ? 'SÍ' : 'no'));
        $this->line("  isBase()       : " . ($period->isBase() ? 'SÍ' : 'no'));
        $this->line("  isMonthly()    : " . ($period->isMonthly() ? 'SÍ' : 'no'));
        $this->line("  isAutoGenerated: " . ($period->isAutoGenerated() ? 'SÍ' : 'no'));
        $this->line("  canReceiveUploads: " . ($period->canReceiveUploads() ? '<fg=green>SÍ</>' : '<fg=red>NO</>'));
        $this->line('');

        // ── component_period_ids ───────────────────────────────────────
        $componentIds = collect($period->component_period_ids ?? [])->map(fn ($id) => (int) $id)->all();
        if (!empty($componentIds)) {
            $componentLabels = $allPeriods->whereIn('id', $componentIds)->map(fn ($p) => "#{$p->id} {$p->label}")->join(', ');
            $this->info('── Semanas configuradas (component_period_ids) ──');
            $this->line("  IDs    : [" . implode(', ', $componentIds) . "]");
            $this->line("  Labels : {$componentLabels}");
        } else {
            $this->warn('── component_period_ids: VACÍO — este mes no tiene semanas asociadas.');
        }
        $this->line('');

        // ── Resolución de IDs base para queries de datos ───────────────
        $dataIds = $period->resolveBaseWeeklyIds($allPeriods);
        if (empty($dataIds)) {
            $dataIds = [$period->id];
        }
        $this->info('── IDs usados para queries de datos (resolveBaseWeeklyIds) ──');
        $this->line("  [" . implode(', ', $dataIds) . "]");
        $this->line('');

        // ── Fuentes activas en data_sources ───────────────────────────
        $allSources   = DataSource::query()->orderBy('name')->get();
        $activeSources = $allSources->where('is_active', true);

        $this->info('── data_sources en BD ──');
        $this->line(sprintf('  %-6s %-30s %-10s %-10s %-12s', 'ID', 'CODE', 'ACTIVA', 'Req.BD', 'Req.Reporte'));
        $this->line('  ' . str_repeat('─', 74));
        foreach ($allSources as $s) {
            $this->line(sprintf(
                '  %-6s %-30s %-10s %-10s %-12s',
                $s->id,
                $s->code,
                $s->is_active  ? '<fg=green>sí</>'  : '<fg=red>no</>',
                $s->is_required_for_bd     ? '<fg=yellow>sí</>' : 'no',
                $s->is_required_for_report ? '<fg=yellow>sí</>' : 'no',
            ));
        }
        $this->line('');
        $this->line("  Activas en UI : {$activeSources->count()} fuentes");
        $this->line("  Req. para BD  : {$activeSources->where('is_required_for_bd', true)->count()} fuentes");
        $this->line("  Req. Radiograf: {$activeSources->where('is_required_for_report', true)->count()} fuentes");
        $this->line('');

        // ── Uploads encontrados ────────────────────────────────────────
        $searchIds = array_values(array_unique(array_merge($dataIds, [$period->id])));

        $uploads = ReportUpload::query()
            ->with('dataSource:id,code,name')
            ->get()
            ->filter(function (ReportUpload $upload) use ($searchIds) {
                $coveredIds = collect($upload->covered_period_ids ?? [])->map(fn ($id) => (int) $id);
                if ($coveredIds->isNotEmpty()) {
                    return $coveredIds->intersect($searchIds)->isNotEmpty();
                }
                return in_array((int) $upload->period_id, $searchIds, true);
            })
            ->sortByDesc('id')
            ->values();

        $this->info('── Uploads encontrados para este periodo ──');
        if ($uploads->isEmpty()) {
            $this->warn('  No hay uploads registrados para este periodo.');
        } else {
            $this->line(sprintf('  %-6s %-28s %-14s %-22s %-30s', 'ID', 'FUENTE', 'ESTADO', 'FECHA', 'ARCHIVO'));
            $this->line('  ' . str_repeat('─', 104));
            foreach ($uploads as $u) {
                $covered = implode(',', collect($u->covered_period_ids ?? [])->all());
                $this->line(sprintf(
                    '  %-6s %-28s %-14s %-22s %-30s',
                    $u->id,
                    mb_substr($u->dataSource?->code ?? '?', 0, 28),
                    $u->status?->value ?? $u->status ?? '?',
                    optional($u->created_at)->format('d/m/Y H:i'),
                    mb_substr($u->original_name ?? '?', 0, 30),
                ));
                if ($covered) $this->line("         covered_period_ids: [{$covered}]");
            }
        }
        $this->line('');

        // ── Estado por fuente activa ───────────────────────────────────
        $this->info('── Estado por fuente activa ──');
        $this->line(sprintf('  %-32s %-14s %-14s %-14s %-30s', 'FUENTE', 'Req.BD', 'Req.Radio', 'ESTADO', 'ARCHIVO'));
        $this->line('  ' . str_repeat('─', 110));

        $missingBd     = [];
        $missingReport = [];

        foreach ($activeSources as $source) {
            $upload = $uploads->first(fn ($u) => $u->dataSource?->code === $source->code);

            [$statusStr, $fileStr] = $upload
                ? [
                    match ((string) ($upload->status?->value ?? $upload->status)) {
                        'processed'  => '<fg=green>procesado</>',
                        'pending'    => '<fg=yellow>pendiente</>',
                        'processing' => '<fg=cyan>procesando</>',
                        'failed'     => '<fg=red>error</>',
                        default      => (string) ($upload->status?->value ?? $upload->status),
                    },
                    mb_substr($upload->original_name ?? '—', 0, 30),
                ]
                : ['<fg=red>FALTANTE</>', '—'];

            $this->line(sprintf(
                '  %-32s %-14s %-14s %-14s %-30s',
                mb_substr($source->name, 0, 32),
                $source->is_required_for_bd     ? '<fg=yellow>SÍ</>' : 'no',
                $source->is_required_for_report ? '<fg=yellow>SÍ</>' : 'no',
                $statusStr,
                $fileStr,
            ));

            if (!$upload) {
                if ($source->is_required_for_bd)     $missingBd[]     = $source->code;
                if ($source->is_required_for_report)  $missingReport[] = $source->code;
            }
        }
        $this->line('');

        // ── Resumen final ──────────────────────────────────────────────
        $this->info('── Resumen ──');
        $uploadedCodes = $uploads->map(fn ($u) => $u->dataSource?->code)->filter()->unique()->values();
        $this->line("  Fuentes activas en UI : {$activeSources->count()}");
        $this->line("  Fuentes cargadas      : {$uploadedCodes->count()}");
        $this->line("  Fuentes procesadas    : " . $uploads->filter(fn ($u) => (string)($u->status?->value ?? $u->status) === 'processed')->count());

        if (empty($missingBd)) {
            $this->line('  <fg=green>✓ No faltan fuentes de BD.</fg=green>');
        } else {
            $this->warn("  Faltan para BD      : " . implode(', ', $missingBd));
        }

        if (empty($missingReport)) {
            $this->line('  <fg=green>✓ No faltan fuentes de Radiografía.</fg=green>');
        } else {
            $this->warn("  Faltan para Radiograf: " . implode(', ', $missingReport));
        }

        $this->line('');
        $this->info("══════════════════════════════════════════════════════════");
        $this->line('');

        return self::SUCCESS;
    }
}
