<?php

namespace App\Http\Requests;

use App\Models\DataSource;
use App\Models\Period;
use Illuminate\Foundation\Http\FormRequest;

class StoreReportUploadRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'period_id' => [
                'required',
                'exists:periods,id',
            ],
            'covered_period_ids' => [
                'required',
                'array',
                'min:1',
            ],
            'covered_period_ids.*' => [
                'integer',
                'exists:periods,id',
            ],
            'data_source_id' => [
                'required',
                'exists:data_sources,id',
            ],
            'file' => [
                'required',
                'file',
                $this->allowedMimes(),
                'max:131072',
            ],
            'notes' => [
                'nullable',
                'string',
            ],
        ];
    }

    private function allowedMimes(): string
    {
        $source = DataSource::query()->find($this->integer('data_source_id'));
        if ($source?->code === 'gastos_lendus') {
            return 'mimes:pdf';
        }
        return 'mimes:xls,xlsx,xlsm';
    }

    public function withValidator($validator): void
    {
        $validator->after(function ($validator) {
            $anchorPeriod = Period::query()->find($this->integer('period_id'));

            if (!$anchorPeriod) {
                return;
            }

            if ($anchorPeriod->type === 'weekly') {
                $validator->errors()->add('period_id', 'Los archivos se suben al mes operativo que agrupa esta semana, no directamente a la semana.');
                return;
            }

            if ($anchorPeriod->isAutoGenerated()) {
                $validator->errors()->add('period_id', 'Este periodo es automático y no recibe archivos directos. Sube los archivos al mes operativo correspondiente.');
                return;
            }

            if (!$anchorPeriod->isMonthly()) {
                $validator->errors()->add('period_id', 'Solo se pueden subir archivos a meses operativos configurados.');
                return;
            }

            if (empty($anchorPeriod->component_period_ids)) {
                $validator->errors()->add('period_id', 'Este mes operativo no tiene semanas configuradas. Ve a Periodos para asociar las semanas correspondientes.');
                return;
            }

            $coveredIds = collect($this->input('covered_period_ids', []))
                ->map(fn ($id) => (int) $id)
                ->unique()
                ->values();

            $coveredPeriods = Period::query()
                ->whereIn('id', $coveredIds)
                ->get();

            if ($coveredPeriods->isEmpty()) {
                $validator->errors()->add('covered_period_ids', 'Debes seleccionar al menos un periodo cubierto.');
                return;
            }

            $validComponentIds = collect($anchorPeriod->component_period_ids)->map(fn ($id) => (int) $id);
            $invalidCovered    = $coveredPeriods->first(fn ($p) => !$validComponentIds->contains((int) $p->id));

            if ($invalidCovered) {
                $validator->errors()->add('covered_period_ids', 'Los periodos cubiertos deben ser semanas del mes operativo seleccionado.');
            }
        });
    }

    public function messages(): array
    {
        return [
            'period_id.required'          => 'Debes seleccionar un mes operativo.',
            'covered_period_ids.required' => 'Debes indicar las semanas que cubre el archivo.',
            'covered_period_ids.array'    => 'Las semanas seleccionadas no son válidas.',
            'covered_period_ids.min'      => 'Selecciona al menos una semana.',
            'data_source_id.required'     => 'Debes seleccionar una fuente.',
            'file.required'               => 'Debes seleccionar un archivo.',
            'file.mimes'                  => 'El archivo no tiene el formato correcto. Gastos Lendus requiere PDF; las demás fuentes requieren XLS/XLSX.',
        ];
    }
}
