<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreReportUploadRequest;
use App\Jobs\GenerateRadiographyJob;
use App\Jobs\ReprocessPeriodUploadsJob;
use App\Jobs\ReprocessReportUploadJob;
use App\Jobs\UpdatePeriodDatabaseJob;
use App\Models\Branch;
use App\Models\DataSource;
use App\Models\Employee;
use App\Models\Period;
use App\Models\PeriodDatabaseUpdateRun;
use App\Models\PeriodIncident;
use App\Models\PeriodRadiographyRun;
use App\Models\PeriodReprocessRun;
use App\Models\MonthlyEmployeeSummary;
use App\Models\PeriodSummary;
use App\Models\ReportUpload;
use App\Services\ReportUploadService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Storage;
use Inertia\Inertia;
use Inertia\Response;

class ReportUploadController extends Controller {

    public function index(): Response {
        // Fuentes activas con sus flags de requerimiento
        $sources = DataSource::query()
            ->where('is_active', true)
            ->orderBy('name')
            ->get(['id', 'code', 'name', 'description', 'is_required_for_bd', 'is_required_for_report']);

        $bdSourceCodes      = $sources->where('is_required_for_bd', true)->pluck('code')->values()->all();
        $reportSourceCodes  = $sources->where('is_required_for_report', true)->pluck('code')->values()->all();

        $summariesByPeriod     = PeriodSummary::query()->with('incidents')->get()->keyBy('period_id');
        $runsByPeriod          = PeriodRadiographyRun::query()->orderByDesc('id')->get()->unique('period_id')->keyBy('period_id');
        $dbRunsByPeriod        = PeriodDatabaseUpdateRun::query()->orderByDesc('id')->get()->unique('period_id')->keyBy('period_id');
        $reprocessRunsByPeriod = PeriodReprocessRun::query()->orderByDesc('id')->get()->unique('period_id')->keyBy('period_id');

        // Cargar TODOS los periodos para resolución recursiva de componentes
        $allPeriods    = Period::query()->orderByDesc('year')->orderByDesc('month')->orderByDesc('sequence')->get();
        $weeklyPeriods = $allPeriods->where('type', 'weekly')->values();

        $periods = $allPeriods->map(function (Period $period) use (
            $allPeriods, $weeklyPeriods, $sources, $bdSourceCodes, $reportSourceCodes,
            $summariesByPeriod, $runsByPeriod, $dbRunsByPeriod, $reprocessRunsByPeriod
        ) {
            $coveredWeeks         = $this->resolveCoveredWeeks($period, $allPeriods);
            $uploads              = $this->resolveUploadsForWeeks($coveredWeeks);
            $uploadedSourceCodes  = $uploads->pluck('dataSource.code')->filter()->unique()->values();
            $missingSources       = $sources->where('is_required_for_report', true)->whereNotIn('code', $uploadedSourceCodes)->pluck('name')->values();
            $summary              = $summariesByPeriod->get($period->id);
            $run                  = $runsByPeriod->get($period->id);
            $dbRun                = $dbRunsByPeriod->get($period->id);
            $reprocessRun         = $reprocessRunsByPeriod->get($period->id);

            $componentLabels = [];
            if (!empty($period->component_period_ids)) {
                $componentLabels = $allPeriods
                    ->whereIn('id', collect($period->component_period_ids)->map(fn ($id) => (int) $id)->all())
                    ->pluck('label')
                    ->values()
                    ->all();
            }

            return [
                'id'                  => $period->id,
                'code'                => $period->code,
                'label'               => $period->label,
                'type'                => $period->type,
                'year'                => $period->year,
                'month'               => $period->month,
                'is_closed'           => (bool) $period->is_closed,
                'can_receive_uploads' => $period->canReceiveUploads(),
                'is_derived'          => $period->isAutoGenerated(),
                'is_compound'         => $period->isCompound(),
                'component_period_ids' => $period->component_period_ids ?? [],
                'component_labels'    => $componentLabels,
                'start_date'          => optional($period->start_date)->format('Y-m-d'),
                'end_date'            => optional($period->end_date)->format('Y-m-d'),
                'updated_at'          => optional($uploads->sortByDesc('created_at')->first()?->created_at)->format('d/m/Y H:i'),
                'uploaded_sources_count' => $uploadedSourceCodes->count(),
                'required_sources_count' => $sources->where('is_required_for_report', true)->count(),
                'missing_sources_count'  => $missingSources->count(),
                'processed_count'        => $uploads->where('status', 'processed')->count(),
                'pending_count'          => $uploads->whereIn('status', ['pending', 'processing'])->count(),
                'failed_count'           => $uploads->where('status', 'failed')->count(),
                'missing_sources'        => $missingSources,
                'report_final_available' => $missingSources->count() === 0 && $sources->where('is_required_for_report', true)->count() > 0,
                'radiography_status'         => $summary?->status ?? 'missing',
                'radiography_invalidated'    => (bool) $summary?->invalidated_at,
                'radiography_run_status'     => $run?->status,
                'radiography_run_log'        => $run?->log,
                'radiography_run_id'         => $run?->id,
                'radiography_run_finished_at'=> optional($run?->finished_at)->format('d/m/Y H:i'),
                'reprocess_run_status'       => $reprocessRun?->status,
                'reprocess_run_log'          => $reprocessRun?->log,
                'reprocess_run_progress'     => $reprocessRun?->metadata['progress'] ?? null,
                'reprocess_run_id'           => $reprocessRun?->id,
                ...$this->resolveWorkflowState($uploads, $summary, $run, $period->isCompound(), $dbRun, $bdSourceCodes, $reportSourceCodes),
                'available_week_options' => $period->canReceiveUploads()
                    ? (
                        $period->isMonthly() && !empty($period->component_period_ids)
                            ? $allPeriods->whereIn('id', collect($period->component_period_ids)->map(fn ($id) => (int) $id)->all())->sortBy('sequence')->map(fn ($week) => [
                                'id'         => $week->id,
                                'label'      => $week->label,
                                'sequence'   => $week->sequence,
                                'start_date' => optional($week->start_date)->format('Y-m-d'),
                                'end_date'   => optional($week->end_date)->format('Y-m-d'),
                            ])->values()
                            : $weeklyPeriods->where('year', $period->year)->where('month', $period->month)->sortBy('sequence')->map(fn ($week) => [
                                'id'         => $week->id,
                                'label'      => $week->label,
                                'sequence'   => $week->sequence,
                                'start_date' => optional($week->start_date)->format('Y-m-d'),
                                'end_date'   => optional($week->end_date)->format('Y-m-d'),
                            ])->values()
                      )
                    : collect(),
                'source_periods' => $coveredWeeks->map(fn ($week) => [
                    'id'                     => $week->id,
                    'label'                  => $week->label,
                    'start_date'             => optional($week->start_date)->format('Y-m-d'),
                    'end_date'               => optional($week->end_date)->format('Y-m-d'),
                    'uploaded_sources_count' => $this->resolveUploadsForWeeks(collect([$week]))->pluck('dataSource.code')->filter()->unique()->count(),
                    'required_sources_count' => $sources->where('is_required_for_report', true)->count(),
                    'complete'               => $this->resolveUploadsForWeeks(collect([$week]))->filter(fn ($u) => (string) ($u->status?->value ?? $u->status) === 'processed')->pluck('dataSource.code')->filter()->unique()->count() >= $sources->where('is_required_for_report', true)->count(),
                ])->values(),
            ];
        })->values();

        $groupedUploads = $allPeriods->map(function (Period $period) use (
            $allPeriods, $sources, $bdSourceCodes, $reportSourceCodes,
            $summariesByPeriod, $runsByPeriod, $dbRunsByPeriod, $reprocessRunsByPeriod
        ) {
            $coveredWeeks        = $this->resolveCoveredWeeks($period, $allPeriods);
            $uploads             = $this->resolveUploadsForWeeks($coveredWeeks);
            $uploadedSourceCodes = $uploads->pluck('dataSource.code')->filter()->unique()->values();
            $missingSources      = $sources->where('is_required_for_report', true)->whereNotIn('code', $uploadedSourceCodes)->pluck('name')->values();
            $summary             = $summariesByPeriod->get($period->id);
            $run                 = $runsByPeriod->get($period->id);
            $dbRun               = $dbRunsByPeriod->get($period->id);
            $reprocessRun        = $reprocessRunsByPeriod->get($period->id);

            return [
                'period_id'              => $period->id,
                'period_code'            => $period->code,
                'period_label'           => $period->label,
                'updated_at'             => optional($uploads->sortByDesc('created_at')->first()?->created_at)->format('d/m/Y H:i'),
                'uploaded_sources_count' => $uploadedSourceCodes->count(),
                'required_sources_count' => $sources->where('is_required_for_report', true)->count(),
                'missing_sources_count'  => $missingSources->count(),
                'processed_count'        => $uploads->where('status', 'processed')->count(),
                'pending_count'          => $uploads->whereIn('status', ['pending', 'processing'])->count(),
                'failed_count'           => $uploads->where('status', 'failed')->count(),
                'missing_sources'        => $missingSources,
                'report_final_available' => $missingSources->count() === 0 && $sources->where('is_required_for_report', true)->count() > 0,
                'radiography_status'          => $summary?->status ?? 'missing',
                'radiography_invalidated'     => (bool) $summary?->invalidated_at,
                'radiography_run_status'      => $run?->status,
                'radiography_run_log'         => $run?->log,
                'radiography_run_id'          => $run?->id,
                'radiography_run_finished_at' => optional($run?->finished_at)->format('d/m/Y H:i'),
                'reprocess_run_status'        => $reprocessRun?->status,
                'reprocess_run_log'           => $reprocessRun?->log,
                'reprocess_run_progress'      => $reprocessRun?->metadata['progress'] ?? null,
                'reprocess_run_id'            => $reprocessRun?->id,
                ...$this->resolveWorkflowState($uploads, $summary, $run, $period->isCompound(), $dbRun, $bdSourceCodes, $reportSourceCodes),
                'uploads' => $uploads->unique('id')->values()->map(fn ($upload) => [
                    'id'                   => $upload->id,
                    'original_name'        => $upload->original_name,
                    'status'               => (string) ($upload->status?->value ?? $upload->status),
                    'uploaded_at'          => optional($upload->created_at)->format('d/m/Y H:i'),
                    'notes'                => $upload->notes,
                    'source_code'          => $upload->dataSource?->code,
                    'source_name'          => $upload->dataSource?->name,
                    'covered_period_ids'   => $upload->covered_period_ids ?? [],
                    'covered_period_labels'=> collect($upload->covered_period_ids ?? [])
                        ->map(fn ($weekId) => optional($allPeriods->firstWhere('id', (int) $weekId))?->label)
                        ->filter()->values(),
                ]),
            ];
        })->values();

        $currentPeriodId = ($periods->firstWhere('can_receive_uploads', true)['id'] ?? null)
            ?: ($periods->first()['id'] ?? null);

        $branches  = Branch::query()->where('is_active', true)->orderBy('name')->get(['id', 'name']);
        $employees = Employee::query()->where('is_active', true)->orderBy('full_name')
            ->with(['employeeBranchAssignments' => fn ($q) => $q->with('branch:id,name')->latest()])
            ->get(['id', 'full_name', 'normalized_name'])
            ->unique(fn (Employee $e) => $e->normalized_name ?: mb_strtolower(trim($e->full_name)))
            ->values()
            ->map(fn (Employee $e) => [
                'id'          => $e->id,
                'full_name'   => $e->full_name,
                'branch_name' => $e->employeeBranchAssignments->first()?->branch?->name,
            ]);

        return Inertia::render('historico-general/index', [
            'periods'         => $periods,
            'sources'         => $sources,
            'groupedUploads'  => $groupedUploads,
            'currentPeriodId' => $currentPeriodId,
            'preview'         => $this->previewPayload($allPeriods->firstWhere('id', $currentPeriodId)),
            'branches'        => $branches,
            'employees'       => $employees,
        ]);
    }

    public function store(StoreReportUploadRequest $request, ReportUploadService $service): RedirectResponse
    {
        $period = Period::query()->findOrFail((int) $request->integer('period_id'));

        if (!$period->canReceiveUploads()) {
            return back()->with('error', 'Este periodo es automático (bimestral/trimestral/etc.) y no recibe archivos directos.');
        }

        $coveredPeriodIds = collect($request->input('covered_period_ids', []))->map(fn ($id) => (int) $id)->filter()->values()->all();

        // Auto-populate covered_period_ids for monthly periods when not provided
        if ($period->isMonthly() && empty($coveredPeriodIds)) {
            $coveredPeriodIds = collect($period->component_period_ids ?? [])->map(fn ($id) => (int) $id)->values()->all();
        }

        $service->store(
            (int) $request->integer('period_id'),
            $coveredPeriodIds,
            (int) $request->integer('data_source_id'),
            $request->file('file'),
            $request->string('notes')->toString() ?: null
        );

        return back()->with('success', 'Archivo subido correctamente.');
    }

    public function destroy(ReportUpload $reportUpload): RedirectResponse
    {
        if ($reportUpload->stored_path && Storage::disk('public')->exists($reportUpload->stored_path)) {
            Storage::disk('public')->delete($reportUpload->stored_path);
        }
        $reportUpload->delete();
        return back()->with('success', 'Archivo eliminado correctamente.');
    }

    public function updateDatabase(Period $period): RedirectResponse
    {
        $existingRun = PeriodDatabaseUpdateRun::query()
            ->where('period_id', $period->id)
            ->whereIn('status', ['queued', 'running'])
            ->first();

        if ($existingRun) {
            return back()->with('error', 'Ya hay una actualización en proceso para este periodo. Espera a que termine.');
        }

        $allPeriods   = Period::query()->get();
        $coveredWeeks = $this->resolveCoveredWeeks($period, $allPeriods);
        $uploads      = $this->resolveUploadsForWeeks($coveredWeeks);
        $summary      = PeriodSummary::query()->where('period_id', $period->id)->first();

        $bdSourceCodes = DataSource::query()
            ->where('is_active', true)
            ->where('is_required_for_bd', true)
            ->pluck('code')
            ->values()
            ->all();

        $workflow = $this->resolveWorkflowState($uploads, $summary, null, $period->isCompound(), null, $bdSourceCodes, []);

        if (!$workflow['can_update_database']) {
            return back()->with('error', implode(' ', $workflow['blocking_reasons']) ?: 'Faltan fuentes obligatorias para actualizar la BD.');
        }

        $run = PeriodDatabaseUpdateRun::query()->create([
            'period_id'  => $period->id,
            'created_by' => auth()->id(),
            'status'     => 'queued',
            'log'        => 'Actualización de base de datos en cola.',
            'started_at' => now(),
        ]);

        UpdatePeriodDatabaseJob::dispatch($period->id, $run->id, auth()->id());

        return back()->with('success', 'El proceso fue enviado a cola. Te avisaremos por correo cuando termine.');
    }

    public function incidents(Period $period)
    {
        $summary = PeriodSummary::query()->where('period_id', $period->id)->with('incidents')->first();

        return response()->json([
            'items'       => $summary?->incidents?->map(fn ($incident) => [
                'id'       => $incident->id,
                'type'     => $incident->type,
                'severity' => $incident->severity,
                'message'  => $incident->message,
                'context'  => $incident->context,
            ])->values() ?? [],
            'has_critical' => (bool) ($summary?->incidents?->contains(fn ($item) => $item->severity === 'high') ?? false),
        ]);
    }

    public function resolveIncident(Period $period, PeriodIncident $incident, Request $request): RedirectResponse
    {
        abort_unless($incident->periodSummary?->period_id === $period->id, 404);

        $incident->update([
            'severity' => 'resolved',
            'context'  => array_merge($incident->context ?? [], [
                'resolved_by'      => auth()->id(),
                'resolved_at'      => now()->toDateTimeString(),
                'resolution_note'  => (string) $request->input('resolution_note', 'Resuelta manualmente.'),
            ]),
        ]);

        return back()->with('success', 'Incidencia resuelta correctamente.');
    }

    public function generateRadiography(Period $period, Request $request): RedirectResponse
    {
        $allPeriods   = Period::query()->get();
        $coveredWeeks = $this->resolveCoveredWeeks($period, $allPeriods);
        $uploads      = $this->resolveUploadsForWeeks($coveredWeeks);
        $summary      = PeriodSummary::query()->where('period_id', $period->id)->with('incidents')->first();
        $latestRun    = PeriodRadiographyRun::query()->where('period_id', $period->id)->latest('id')->first();

        $bdSourceCodes     = DataSource::query()->where('is_active', true)->where('is_required_for_bd', true)->pluck('code')->values()->all();
        $reportSourceCodes = DataSource::query()->where('is_active', true)->where('is_required_for_report', true)->pluck('code')->values()->all();

        $workflow = $this->resolveWorkflowState($uploads, $summary, $latestRun, $period->isCompound(), null, $bdSourceCodes, $reportSourceCodes);

        if (!$workflow['can_generate_radiography']) {
            return back()->with('error', implode(' ', $workflow['blocking_reasons']) ?: 'No se puede generar la Radiografía todavía.');
        }

        $run = PeriodRadiographyRun::query()->create([
            'period_id'  => $period->id,
            'status'     => 'queued',
            'started_at' => now(),
            'created_by' => auth()->id(),
            'log'        => 'Radiografía en cola. Puedes cerrar esta ventana.',
        ]);

        $config = $request->input('config', []);
        $scope  = $config['scope'] ?? 'general';
        $type   = ($config['report_type'] ?? 'simple') === 'simple' ? 'Radiografía simple' : 'Reporte comparativo';
        $run->forceFill(['log' => "Radiografía en cola. Se generará un {$type} con alcance {$scope}."])->save();

        GenerateRadiographyJob::dispatch($period->id, auth()->id(), $run->id, $config);

        return back()->with('success', 'La Radiografía se está generando en segundo plano. Recibirás un correo cuando esté lista.');
    }

    public function analyze(ReportUpload $reportUpload): RedirectResponse
    {
        $sourceCode = $reportUpload->dataSource?->code ?? '';
        $sourceName = $reportUpload->dataSource?->name ?? 'La fuente';

        $bdSourceCodes = DataSource::query()->where('is_active', true)->where('is_required_for_bd', true)->pluck('code')->values()->all();
        $isBdSource    = in_array($sourceCode, $bdSourceCodes, true);

        $summary = PeriodSummary::query()
            ->where('period_id', $reportUpload->period_id)
            ->whereNull('invalidated_at')
            ->first();

        if ($summary && $isBdSource) {
            $summary->update([
                'invalidated_at'     => now(),
                'invalidated_by'     => auth()->id(),
                'invalidated_reason' => "Fuente de BD reprocesada: {$sourceName}. La actualización de BD debe ejecutarse nuevamente.",
            ]);
        } elseif ($summary && !$isBdSource && $summary->status === 'generated') {
            $summary->update([
                'status'             => 'database_updated',
                'invalidated_reason' => "Fuente reprocesada: {$sourceName}. Re-genera la Radiografía para reflejar los cambios.",
            ]);
        }

        ReprocessReportUploadJob::dispatch($reportUpload->id, auth()->id());

        return back()->with('success', "'{$sourceName}' fue enviado a reprocesamiento en cola. Recibirás un correo cuando termine.");
    }

    public function reprocessAll(Period $period): RedirectResponse
    {
        $existing = PeriodReprocessRun::query()
            ->where('period_id', $period->id)
            ->whereIn('status', ['queued', 'running'])
            ->first();

        if ($existing) {
            return back()->with('error', 'Ya hay un reprocesamiento en curso para este periodo. Espera a que termine.');
        }

        $summary = PeriodSummary::query()
            ->where('period_id', $period->id)
            ->whereNull('invalidated_at')
            ->first();

        if ($summary) {
            $summary->update([
                'invalidated_at'     => now(),
                'invalidated_by'     => auth()->id(),
                'invalidated_reason' => 'Todo el periodo fue enviado a reprocesamiento.',
            ]);
        }

        $allPeriods      = Period::query()->get();
        $coveredWeeks    = $this->resolveCoveredWeeks($period, $allPeriods);
        $coveredPeriodIds = $coveredWeeks->pluck('id')->map(fn ($id) => (int) $id)->values()->all();

        $run = PeriodReprocessRun::query()->create([
            'period_id'  => $period->id,
            'created_by' => auth()->id(),
            'status'     => 'queued',
            'log'        => 'Reprocesamiento completo del periodo en cola.',
            'metadata'   => ['progress' => 0],
            'started_at' => now(),
        ]);

        ReprocessPeriodUploadsJob::dispatch($period->id, $run->id, $coveredPeriodIds, auth()->id());

        return back()->with('success', 'El reprocesamiento completo fue enviado a cola. Recibirás un correo cuando termine.');
    }

    public function cancelDatabaseUpdate(Period $period): RedirectResponse
    {
        $run = PeriodDatabaseUpdateRun::query()
            ->where('period_id', $period->id)
            ->whereIn('status', ['queued', 'running'])
            ->latest('id')
            ->first();

        if (!$run) {
            return back()->with('error', 'No hay un proceso activo para cancelar en este periodo.');
        }

        $cancelledBy = auth()->user()?->name ?? 'usuario';
        $run->update([
            'status'        => 'failed',
            'finished_at'   => now(),
            'log'           => "Proceso cancelado manualmente por {$cancelledBy}.",
            'error_message' => 'Cancelado manualmente.',
        ]);

        return back()->with('success', 'El proceso fue cancelado. Puedes reintentarlo cuando estés listo.');
    }

    // ── Helpers privados ──────────────────────────────────────────────

    private function previewPayload(?Period $period): array
    {
        if (!$period) {
            return ['metrics' => [], 'employees' => []];
        }

        $summary = MonthlyEmployeeSummary::query()
            ->where('period_id', $period->id)
            ->selectRaw('COUNT(*) as total_empleados')
            ->selectRaw('SUM(total_expenses) as gasto_total')
            ->selectRaw('SUM(net_amount) as neto_total')
            ->selectRaw('SUM(total_payments) as pagos_total')
            ->first();

        return [
            'metrics' => [
                'total_empleados' => (int) ($summary->total_empleados ?? 0),
                'gasto_total'     => (float) ($summary->gasto_total ?? 0),
                'neto_total'      => (float) ($summary->neto_total ?? 0),
                'pagos_total'     => (float) ($summary->pagos_total ?? 0),
            ],
            'employees' => MonthlyEmployeeSummary::query()
                ->with(['employee:id,full_name', 'branch:id,name'])
                ->where('period_id', $period->id)
                ->limit(50)
                ->get()
                ->map(fn (MonthlyEmployeeSummary $row) => [
                    'id'             => $row->id,
                    'employee_name'  => $row->employee?->full_name ?? 'Sin empleado',
                    'branch_name'    => $row->branch?->name,
                    'total_payments' => (float) $row->total_payments,
                    'total_expenses' => (float) $row->total_expenses,
                    'net_amount'     => (float) $row->net_amount,
                ])->values(),
        ];
    }

    // Resolución recursiva: retorna los periodos SEMANALES que componen el periodo dado.
    // Usa component_period_ids cuando existe; hace fallback por fecha en caso contrario.
    private function resolveCoveredWeeks(Period $period, Collection $allPeriods): Collection
    {
        if ($period->isBase()) {
            return $allPeriods->where('id', $period->id)->values();
        }

        $weeklyIds = $period->resolveBaseWeeklyIds($allPeriods);

        return $allPeriods->whereIn('id', $weeklyIds)->where('type', 'weekly')->values();
    }

    private function resolveUploadsForWeeks(Collection $coveredWeeks): Collection
    {
        if ($coveredWeeks->isEmpty()) return collect();

        $weekIds = $coveredWeeks->pluck('id')->map(fn ($id) => (int) $id)->values()->all();

        return ReportUpload::query()
            ->with('dataSource:id,code,name')
            ->get()
            ->filter(function (ReportUpload $upload) use ($weekIds) {
                $coveredIds = collect($upload->covered_period_ids ?? [])
                    ->map(fn ($id) => (int) $id);

                if ($coveredIds->isNotEmpty()) {
                    return $coveredIds->intersect($weekIds)->isNotEmpty();
                }

                return in_array((int) $upload->period_id, $weekIds, true);
            })
            ->sortByDesc('created_at')
            ->values();
    }

    private function resolveWorkflowState(
        Collection            $uploads,
        ?PeriodSummary        $summary,
        ?PeriodRadiographyRun $run          = null,
        bool                  $compoundPeriod = false,
        ?PeriodDatabaseUpdateRun $dbRun     = null,
        array                 $bdSourceCodes = [],
        array                 $reportSourceCodes = [],
    ): array {
        $sourceCodes = $uploads->pluck('dataSource.code')->filter()->unique()->values();

        $missingDb = collect($bdSourceCodes)
            ->filter(fn ($code) => !$sourceCodes->contains($code))
            ->values()
            ->all();

        $missingRadiography = collect($reportSourceCodes)
            ->filter(fn ($code) => !$sourceCodes->contains($code))
            ->values()
            ->all();

        $failedDb = collect($bdSourceCodes)->filter(function ($code) use ($uploads) {
            $upload = $uploads->first(fn ($item) => $item->dataSource?->code === $code);
            return $upload && (string) ($upload->status?->value ?? $upload->status) === 'failed';
        })->values()->all();

        $unprocessedRadiography = collect($reportSourceCodes)->filter(function ($code) use ($uploads) {
            $upload = $uploads->first(fn ($item) => $item->dataSource?->code === $code);
            if (!$upload) return false;
            return (string) ($upload->status?->value ?? $upload->status) !== 'processed';
        })->values()->all();

        $pendingCritical = (int) ($summary?->incidents()->where('severity', 'high')->count() ?? 0);
        $databaseUpdated = (in_array($summary?->status, ['database_updated', 'generated'], true) && !$summary?->invalidated_at)
            || ($compoundPeriod && empty($missingDb) && empty($failedDb));

        $radiographyReady = ($summary?->status === 'generated') && !$summary?->invalidated_at;
        $runStatus        = $run?->status;
        $running          = in_array($runStatus, ['queued', 'running'], true);
        $dbRunStatus      = $dbRun?->status;
        $dbRunning        = in_array($dbRunStatus, ['queued', 'running'], true);

        $dbElapsedSeconds = null;
        $dbStuckWarning   = false;
        if ($dbRun) {
            if ($dbRunning) {
                $ref = $dbRunStatus === 'queued'
                    ? $dbRun->created_at
                    : ($dbRun->started_at ?? $dbRun->created_at);
                $dbElapsedSeconds = $ref ? max(0, (int) now()->diffInSeconds($ref)) : null;
                $dbStuckWarning   = $dbElapsedSeconds !== null && (
                    ($dbRunStatus === 'queued' && $dbElapsedSeconds >= 300) ||
                    ($dbRunStatus !== 'queued' && $dbElapsedSeconds >= 1800)
                );
            } elseif ($dbRun->started_at && $dbRun->finished_at) {
                $dbElapsedSeconds = max(0, (int) $dbRun->started_at->diffInSeconds($dbRun->finished_at));
            }
        }

        $blockingReasons = [];
        if (!empty($missingDb))         $blockingReasons[] = 'Faltan archivos de BD obligatorios: ' . implode(', ', $missingDb) . '.';
        if (!empty($failedDb))          $blockingReasons[] = 'Fuentes de BD tienen error de procesamiento.';
        if ($dbRunning)                 $blockingReasons[] = 'La actualización de base de datos está en proceso.';
        if (!$databaseUpdated)          $blockingReasons[] = 'Primero actualiza la BD.';
        if ($pendingCritical > 0)       $blockingReasons[] = 'Hay incidencias críticas pendientes.';
        if (!empty($missingRadiography)) $blockingReasons[] = 'Faltan fuentes para generar la Radiografía.';
        if (!empty($unprocessedRadiography)) $blockingReasons[] = 'Hay fuentes sin procesar. Todas deben quedar procesadas.';
        if ($running)                   $blockingReasons[] = 'La Radiografía está en proceso.';

        $previewSummary = null;
        if ($radiographyReady && $summary) {
            $gm = $summary->global_metrics ?? [];

            // If stored global_metrics are all zero, recompute inline from fact tables
            // This happens when the radiography was generated before the period-ID merge fix
            if (($gm['colocacion_total'] ?? 0) == 0 && ($gm['valor_cartera_total'] ?? 0) == 0) {
                $period = \App\Models\Period::find($summary->period_id);
                if ($period) {
                    $allPeriodsLocal = \App\Models\Period::all();
                    $weeklyIdsLocal  = $period->resolveBaseWeeklyIds($allPeriodsLocal);
                    if (empty($weeklyIdsLocal)) {
                        $weeklyIdsLocal = [$period->id];
                    }
                    $dataIdsLocal = array_values(array_unique(array_merge($weeklyIdsLocal, [$period->id])));

                    $ct = (float) \Illuminate\Support\Facades\DB::table('fact_portfolios')->whereIn('period_id', $dataIdsLocal)->sum('balance');
                    $cv = (float) \Illuminate\Support\Facades\DB::table('fact_portfolios')->whereIn('period_id', $dataIdsLocal)->where('days_past_due', '>', 0)->sum('balance');
                    $gm['valor_cartera_total']   = $ct;
                    $gm['cartera_vencida_total'] = $cv;
                    $gm['mora_porcentaje']       = $ct > 0 ? round($cv / $ct * 100, 2) : 0;
                    $gm['colocacion_total']      = (float) \Illuminate\Support\Facades\DB::table('fact_placements')->whereIn('period_id', $dataIdsLocal)->sum('amount');
                    $gm['recuperacion_total']    = (float) \Illuminate\Support\Facades\DB::table('fact_recoveries')->whereIn('period_id', $dataIdsLocal)->sum('total_amount');
                    $gm['gasto_total']           = (float) \Illuminate\Support\Facades\DB::table('fact_expenses')->whereIn('period_id', $dataIdsLocal)->sum('amount');
                    // Payroll from consolidated table (uses period->id directly)
                    $mes = \Illuminate\Support\Facades\DB::table('fact_period_employee_summary')
                        ->where('period_id', $period->id)
                        ->selectRaw('COUNT(*) as cnt, SUM(total_payments) as pagos, SUM(net_amount) as neto')
                        ->first();
                    if ((int)($mes?->cnt ?? 0) > 0) {
                        $gm['total_empleados'] = (int)$mes->cnt;
                        $gm['pagos_total']     = (float)$mes->pagos;
                        $gm['neto_total']      = (float)$mes->neto;
                    } else {
                        $gm['total_empleados'] = (int) \Illuminate\Support\Facades\DB::table('fact_noi_movements')
                            ->whereIn('period_id', $dataIdsLocal)->whereNotNull('employee_id')->distinct('employee_id')->count('employee_id');
                    }
                }
            }

            $previewSummary = [
                'global_metrics' => $gm,
                'generated_at'   => optional($summary->generated_at)->format('d/m/Y H:i'),
                'version'        => $summary->version,
            ];
        }

        return [
            'database_updated'                => $databaseUpdated,
            'database_invalidated'            => (bool) $summary?->invalidated_at,
            'database_update_run_status'      => $dbRunStatus,
            'database_update_run_log'         => $dbRun?->log ? mb_strimwidth($dbRun->log, 0, 300) : null,
            'database_update_run_error'       => $dbRun?->error_message ? mb_strimwidth($dbRun->error_message, 0, 300) : null,
            'database_update_run_started_at'  => optional($dbRun?->started_at)->format('d/m/Y H:i'),
            'database_update_run_finished_at' => optional($dbRun?->finished_at)->format('d/m/Y H:i'),
            'database_update_run_metadata'    => $dbRun?->metadata,
            'database_update_elapsed_seconds' => $dbElapsedSeconds,
            'database_update_stuck_warning'   => $dbStuckWarning,
            'pending_critical_incidents_count' => $pendingCritical,
            'missing_database_sources'        => $missingDb,
            'missing_radiography_sources'     => $missingRadiography,
            'unprocessed_radiography_sources' => $unprocessedRadiography,
            'radiography_ready'               => $radiographyReady,
            'radiography_invalidated'         => (bool) $summary?->invalidated_at,
            'radiography_running'             => $running,
            'can_update_database'             => empty($missingDb) && empty($failedDb) && !$dbRunning,
            'can_resolve_incidents'           => $databaseUpdated,
            'can_generate_radiography'        => $databaseUpdated && $pendingCritical === 0 && empty($missingRadiography) && empty($unprocessedRadiography) && !$running,
            'can_export_radiography'          => $radiographyReady && empty($missingRadiography) && empty($unprocessedRadiography) && !$running,
            'blocking_reasons'                => array_values(array_unique($blockingReasons)),
            'preview_summary'                 => $previewSummary,
        ];
    }
}
