<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreReportUploadRequest;
use App\Jobs\GenerateRadiographyJob;
use App\Jobs\ReprocessPeriodUploadsJob;
use App\Jobs\ReprocessReportUploadJob;
use App\Jobs\UpdatePeriodDatabaseJob;
use App\Models\Branch;
use App\Models\DataSource;
use App\Models\Employee;
use App\Models\Period;
use App\Models\PeriodDatabaseUpdateRun;
use App\Models\PeriodIncident;
use App\Models\PeriodRadiographyRun;
use App\Models\PeriodReprocessRun;
use App\Models\MonthlyEmployeeSummary;
use App\Models\PeriodSummary;
use App\Models\ReportUpload;
use App\Services\ReportUploadService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Inertia\Inertia;
use Inertia\Response;

class ReportUploadController extends Controller {

    /** Las 13 sucursales operativas — fuente de verdad para el selector UI. */
    private const OPERATIVE_BRANCH_NAMES = [
        'ATLACOMULCO', 'ATLIXCO', 'CORDOBA', 'CUERNAVACA', 'HUAMANTLA',
        'IXTLAHUACA', 'MIACATLAN', 'ORIZABA', 'SAN JUAN DEL RÍO',
        'SAN LUIS POTOSI', 'TENANGO DEL VALLE', 'TLAXCALA', 'TULA',
    ];

    public function index(): Response {
        // Fuentes activas con sus flags de requerimiento
        $sources = DataSource::query()
            ->where('is_active', true)
            ->orderBy('name')
            ->get(['id', 'code', 'name', 'description', 'is_required_for_bd', 'is_required_for_report']);

        $bdSourceCodes      = $sources->where('is_required_for_bd', true)->pluck('code')->values()->all();
        $reportSourceCodes  = $sources->where('is_required_for_report', true)->pluck('code')->values()->all();

        $summariesByPeriod     = PeriodSummary::query()->with('incidents')->get()->keyBy('period_id');
        $runsByPeriod          = PeriodRadiographyRun::query()->orderByDesc('id')->get()->unique('period_id')->keyBy('period_id');
        $dbRunsByPeriod        = PeriodDatabaseUpdateRun::query()->orderByDesc('id')->get()->unique('period_id')->keyBy('period_id');
        $reprocessRunsByPeriod = PeriodReprocessRun::query()->orderByDesc('id')->get()->unique('period_id')->keyBy('period_id');

        // Cargar TODOS los periodos para resolución recursiva de componentes
        $allPeriods    = Period::query()->orderByDesc('year')->orderByDesc('month')->orderByDesc('sequence')->get();
        $weeklyPeriods = $allPeriods->where('type', 'weekly')->values();

        $periods = $allPeriods->map(function (Period $period) use (
            $allPeriods, $weeklyPeriods, $sources, $bdSourceCodes, $reportSourceCodes,
            $summariesByPeriod, $runsByPeriod, $dbRunsByPeriod, $reprocessRunsByPeriod
        ) {
            $coveredWeeks         = $this->resolveCoveredWeeks($period, $allPeriods);
            $uploads              = $this->resolveUploadsForWeeks($coveredWeeks);
            $uploadedSourceCodes  = $uploads->pluck('dataSource.code')->filter()->unique()->values();
            $missingSources       = $sources->where('is_required_for_report', true)->whereNotIn('code', $uploadedSourceCodes)->pluck('name')->values();
            $summary              = $summariesByPeriod->get($period->id);
            $run                  = $runsByPeriod->get($period->id);
            $dbRun                = $dbRunsByPeriod->get($period->id);
            $reprocessRun         = $reprocessRunsByPeriod->get($period->id);

            $componentLabels = [];
            if (!empty($period->component_period_ids)) {
                $componentLabels = $allPeriods
                    ->whereIn('id', collect($period->component_period_ids)->map(fn ($id) => (int) $id)->all())
                    ->pluck('label')
                    ->values()
                    ->all();
            }

            return [
                'id'                  => $period->id,
                'code'                => $period->code,
                'label'               => $period->label,
                'type'                => $period->type,
                'year'                => $period->year,
                'month'               => $period->month,
                'is_closed'           => (bool) $period->is_closed,
                'can_receive_uploads' => $period->canReceiveUploads(),
                'is_derived'          => $period->isAutoGenerated(),
                'is_compound'         => $period->isCompound(),
                'component_period_ids' => $period->component_period_ids ?? [],
                'component_labels'    => $componentLabels,
                'start_date'          => optional($period->start_date)->format('Y-m-d'),
                'end_date'            => optional($period->end_date)->format('Y-m-d'),
                'updated_at'          => optional($uploads->sortByDesc('created_at')->first()?->created_at)->format('d/m/Y H:i'),
                'uploaded_sources_count' => $uploadedSourceCodes->count(),
                'required_sources_count' => $sources->where('is_required_for_report', true)->count(),
                'missing_sources_count'  => $missingSources->count(),
                'processed_count'        => $uploads->where('status', 'processed')->count(),
                'pending_count'          => $uploads->whereIn('status', ['pending', 'processing'])->count(),
                'failed_count'           => $uploads->where('status', 'failed')->count(),
                'missing_sources'        => $missingSources,
                'report_final_available' => $missingSources->count() === 0 && $sources->where('is_required_for_report', true)->count() > 0,
                'radiography_status'         => $summary?->status ?? 'missing',
                'radiography_invalidated'    => (bool) $summary?->invalidated_at,
                'radiography_run_status'     => $run?->status,
                'radiography_run_log'        => $run?->log,
                'radiography_run_id'         => $run?->id,
                'radiography_run_finished_at'=> optional($run?->finished_at)->format('d/m/Y H:i'),
                'reprocess_run_status'       => $reprocessRun?->status,
                'reprocess_run_log'          => $reprocessRun?->log,
                'reprocess_run_progress'     => $reprocessRun?->metadata['progress'] ?? null,
                'reprocess_run_id'           => $reprocessRun?->id,
                ...$this->resolveWorkflowState($uploads, $summary, $run, $period->isCompound(), $dbRun, $bdSourceCodes, $reportSourceCodes),
                'available_week_options' => $period->canReceiveUploads()
                    ? (
                        $period->isMonthly() && !empty($period->component_period_ids)
                            ? $allPeriods->whereIn('id', collect($period->component_period_ids)->map(fn ($id) => (int) $id)->all())->sortBy('sequence')->map(fn ($week) => [
                                'id'         => $week->id,
                                'label'      => $week->label,
                                'sequence'   => $week->sequence,
                                'start_date' => optional($week->start_date)->format('Y-m-d'),
                                'end_date'   => optional($week->end_date)->format('Y-m-d'),
                            ])->values()
                            : $weeklyPeriods->where('year', $period->year)->where('month', $period->month)->sortBy('sequence')->map(fn ($week) => [
                                'id'         => $week->id,
                                'label'      => $week->label,
                                'sequence'   => $week->sequence,
                                'start_date' => optional($week->start_date)->format('Y-m-d'),
                                'end_date'   => optional($week->end_date)->format('Y-m-d'),
                            ])->values()
                      )
                    : collect(),
                'source_periods' => $coveredWeeks->map(fn ($week) => [
                    'id'                     => $week->id,
                    'label'                  => $week->label,
                    'start_date'             => optional($week->start_date)->format('Y-m-d'),
                    'end_date'               => optional($week->end_date)->format('Y-m-d'),
                    'uploaded_sources_count' => $this->resolveUploadsForWeeks(collect([$week]))->pluck('dataSource.code')->filter()->unique()->count(),
                    'required_sources_count' => $sources->where('is_required_for_report', true)->count(),
                    'complete'               => $this->resolveUploadsForWeeks(collect([$week]))->filter(fn ($u) => (string) ($u->status?->value ?? $u->status) === 'processed')->pluck('dataSource.code')->filter()->unique()->count() >= $sources->where('is_required_for_report', true)->count(),
                ])->values(),
            ];
        })->values();

        $groupedUploads = $allPeriods->map(function (Period $period) use (
            $allPeriods, $sources, $bdSourceCodes, $reportSourceCodes,
            $summariesByPeriod, $runsByPeriod, $dbRunsByPeriod, $reprocessRunsByPeriod
        ) {
            $coveredWeeks        = $this->resolveCoveredWeeks($period, $allPeriods);
            $uploads             = $this->resolveUploadsForWeeks($coveredWeeks);
            $uploadedSourceCodes = $uploads->pluck('dataSource.code')->filter()->unique()->values();
            $missingSources      = $sources->where('is_required_for_report', true)->whereNotIn('code', $uploadedSourceCodes)->pluck('name')->values();
            $summary             = $summariesByPeriod->get($period->id);
            $run                 = $runsByPeriod->get($period->id);
            $dbRun               = $dbRunsByPeriod->get($period->id);
            $reprocessRun        = $reprocessRunsByPeriod->get($period->id);

            return [
                'period_id'              => $period->id,
                'period_code'            => $period->code,
                'period_label'           => $period->label,
                'updated_at'             => optional($uploads->sortByDesc('created_at')->first()?->created_at)->format('d/m/Y H:i'),
                'uploaded_sources_count' => $uploadedSourceCodes->count(),
                'required_sources_count' => $sources->where('is_required_for_report', true)->count(),
                'missing_sources_count'  => $missingSources->count(),
                'processed_count'        => $uploads->where('status', 'processed')->count(),
                'pending_count'          => $uploads->whereIn('status', ['pending', 'processing'])->count(),
                'failed_count'           => $uploads->where('status', 'failed')->count(),
                'missing_sources'        => $missingSources,
                'report_final_available' => $missingSources->count() === 0 && $sources->where('is_required_for_report', true)->count() > 0,
                'radiography_status'          => $summary?->status ?? 'missing',
                'radiography_invalidated'     => (bool) $summary?->invalidated_at,
                'radiography_run_status'      => $run?->status,
                'radiography_run_log'         => $run?->log,
                'radiography_run_id'          => $run?->id,
                'radiography_run_finished_at' => optional($run?->finished_at)->format('d/m/Y H:i'),
                'reprocess_run_status'        => $reprocessRun?->status,
                'reprocess_run_log'           => $reprocessRun?->log,
                'reprocess_run_progress'      => $reprocessRun?->metadata['progress'] ?? null,
                'reprocess_run_id'            => $reprocessRun?->id,
                ...$this->resolveWorkflowState($uploads, $summary, $run, $period->isCompound(), $dbRun, $bdSourceCodes, $reportSourceCodes),
                'uploads' => $uploads->unique('id')->values()->map(fn ($upload) => [
                    'id'                   => $upload->id,
                    'original_name'        => $upload->original_name,
                    'status'               => (string) ($upload->status?->value ?? $upload->status),
                    'uploaded_at'          => optional($upload->created_at)->format('d/m/Y H:i'),
                    'notes'                => $upload->notes,
                    'source_code'          => $upload->dataSource?->code,
                    'source_name'          => $upload->dataSource?->name,
                    'covered_period_ids'   => $upload->covered_period_ids ?? [],
                    'covered_period_labels'=> collect($upload->covered_period_ids ?? [])
                        ->map(fn ($weekId) => optional($allPeriods->firstWhere('id', (int) $weekId))?->label)
                        ->filter()->values(),
                ]),
            ];
        })->values();

        $currentPeriodId = ($periods->firstWhere('can_receive_uploads', true)['id'] ?? null)
            ?: ($periods->first()['id'] ?? null);

        $branches  = Branch::query()
            ->whereIn('name', self::OPERATIVE_BRANCH_NAMES)
            ->orderBy('name')
            ->get(['id', 'name']);
        // Load employees with their assignment for the CURRENT period only.
        // Using ->latest() without a period_id filter was showing employees as "Sin sucursal"
        // even when they had a valid assignment in a different period.
        $employees = Employee::query()->where('is_active', true)->orderBy('full_name')
            ->with(['employeeBranchAssignments' => fn ($q) => $q
                ->where('period_id', $currentPeriodId)
                ->with('branch:id,name')
            ])
            ->get(['id', 'full_name', 'normalized_name'])
            ->unique(fn (Employee $e) => $e->normalized_name ?: mb_strtolower(trim($e->full_name)))
            ->values()
            ->map(fn (Employee $e) => [
                'id'          => $e->id,
                'full_name'   => $e->full_name,
                'branch_name' => $e->employeeBranchAssignments->first()?->branch?->name,
            ]);

        return Inertia::render('Historico-General/index', [
            'periods'         => $periods,
            'sources'         => $sources,
            'groupedUploads'  => $groupedUploads,
            'currentPeriodId' => $currentPeriodId,
            'preview'         => $this->previewPayload($allPeriods->firstWhere('id', $currentPeriodId)),
            'branches'        => $branches,
            'employees'       => $employees,
        ]);
    }

    public function store(StoreReportUploadRequest $request, ReportUploadService $service): RedirectResponse
    {
        $period = Period::query()->findOrFail((int) $request->integer('period_id'));

        if (!$period->canReceiveUploads()) {
            return back()->with('error', 'Este periodo es automático (bimestral/trimestral/etc.) y no recibe archivos directos.');
        }

        $coveredPeriodIds = collect($request->input('covered_period_ids', []))->map(fn ($id) => (int) $id)->filter()->values()->all();

        // Auto-populate covered_period_ids for monthly periods when not provided
        if ($period->isMonthly() && empty($coveredPeriodIds)) {
            $coveredPeriodIds = collect($period->component_period_ids ?? [])->map(fn ($id) => (int) $id)->values()->all();
        }

        $service->store(
            (int) $request->integer('period_id'),
            $coveredPeriodIds,
            (int) $request->integer('data_source_id'),
            $request->file('file'),
            $request->string('notes')->toString() ?: null
        );

        return back()->with('success', 'Archivo subido correctamente.');
    }

    public function destroy(ReportUpload $reportUpload): RedirectResponse
    {
        if ($reportUpload->stored_path && Storage::disk('public')->exists($reportUpload->stored_path)) {
            Storage::disk('public')->delete($reportUpload->stored_path);
        }
        $reportUpload->delete();
        return back()->with('success', 'Archivo eliminado correctamente.');
    }

    public function updateDatabase(Period $period): RedirectResponse
    {
        $existingRun = PeriodDatabaseUpdateRun::query()
            ->where('period_id', $period->id)
            ->whereIn('status', ['queued', 'running'])
            ->first();

        if ($existingRun) {
            throw \Illuminate\Validation\ValidationException::withMessages([
                'period' => 'Ya hay una carga en proceso o en cola para este periodo.',
            ]);
        }

        $allPeriods   = Period::query()->get();
        $coveredWeeks = $this->resolveCoveredWeeks($period, $allPeriods);
        $uploads      = $this->resolveUploadsForWeeks($coveredWeeks);
        $summary      = PeriodSummary::query()->where('period_id', $period->id)->first();

        $bdSourceCodes = DataSource::query()
            ->where('is_active', true)
            ->where('is_required_for_bd', true)
            ->pluck('code')
            ->values()
            ->all();

        $workflow = $this->resolveWorkflowState($uploads, $summary, null, $period->isCompound(), null, $bdSourceCodes, []);

        if (!$workflow['can_update_database']) {
            return back()->with('error', implode(' ', $workflow['blocking_reasons']) ?: 'Faltan fuentes obligatorias para actualizar la BD.');
        }

        $run = PeriodDatabaseUpdateRun::query()->create([
            'period_id'  => $period->id,
            'created_by' => auth()->id(),
            'status'     => 'queued',
            'log'        => 'Carga de registros en cola.',
            'queued_at'  => now(),
            'started_at' => null,
        ]);

        UpdatePeriodDatabaseJob::dispatch($period->id, $run->id, auth()->id());

        return back()->with('success', 'El proceso fue enviado a cola. Te avisaremos por correo cuando termine.');
    }

    public function incidents(Period $period)
    {
        $allPeriods = Period::all();
        $weeklyIds  = $period->resolveBaseWeeklyIds($allPeriods);
        $dataIds    = array_values(array_unique(array_merge(
            empty($weeklyIds) ? [] : $weeklyIds,
            [$period->id]
        )));

        // Guard: if fact tables are empty, there's no real data to validate incidents against.
        // Return a clear "no data" state instead of 0 incidents (which is misleading).
        $hasFactData = DB::table('fact_noi_movements')->whereIn('period_id', $dataIds)->exists()
                    || DB::table('fact_recoveries')->whereIn('period_id', $dataIds)->exists();

        if (!$hasFactData) {
            return response()->json([
                'items'        => [],
                'has_critical' => false,
                'has_data'     => false,
                'message'      => 'Sin registros procesados para este periodo. Ejecuta primero "Cargar registros" (Etapa 2) para que las incidencias puedan calcularse.',
            ]);
        }

        // Lightweight refreshes: keep both counters in sync without full radiography
        $this->refreshEmpleadosSinSucursalIncident($period, $dataIds);
        $this->refreshCoincidenciasIncident($period, $dataIds);

        $summary = PeriodSummary::query()->where('period_id', $period->id)->with('incidents')->first();

        $items = $summary?->incidents
            ?->filter(fn ($i) => !in_array($i->type, ['mora_alta', 'db_update.mora_alta'], true))
            ->map(fn ($incident) => [
                'id'       => $incident->id,
                'type'     => $incident->type,
                'severity' => $incident->severity,
                'message'  => $incident->message,
                'context'  => $incident->context,
            ])->values() ?? collect();

        return response()->json([
            'items'        => $items,
            'has_critical' => (bool) ($items->contains(fn ($item) => $item['severity'] === 'high') ?? false),
            'has_data'     => true,
        ]);
    }

    /**
     * Re-run the incidents calculation for a period and return the fresh list.
     * Called after an employee branch assignment to reflect the updated state.
     */
    public function refreshIncidents(Period $period)
    {
        /** @var \App\Services\PeriodRadiographyService $svc */
        $svc = app(\App\Services\PeriodRadiographyService::class);
        $summary = $svc->generate($period);

        $items = $summary->incidents
            ->filter(fn ($i) => !in_array($i->type, ['mora_alta', 'db_update.mora_alta'], true))
            ->map(fn ($incident) => [
                'id'       => $incident->id,
                'type'     => $incident->type,
                'severity' => $incident->severity,
                'message'  => $incident->message,
                'context'  => $incident->context,
            ])->values();

        return response()->json([
            'items'        => $items,
            'has_critical' => (bool) $items->contains(fn ($item) => $item['severity'] === 'high'),
        ]);
    }

    public function personasSinSucursal(Period $period)
    {
        $allPeriods = Period::all();
        $weeklyIds  = $period->resolveBaseWeeklyIds($allPeriods);
        $dataIds    = array_values(array_unique(array_merge(
            empty($weeklyIds) ? [] : $weeklyIds,
            [$period->id]
        )));

        // Guard: if fact_noi_movements is empty, return no_data state.
        // This prevents showing a stale cached list in Vue or an empty list that
        // looks like "all employees are assigned" when data simply wasn't loaded.
        $hasNoi = DB::table('fact_noi_movements')->whereIn('period_id', $dataIds)->exists();
        if (!$hasNoi) {
            return response()->json([
                'items'   => [],
                'no_data' => true,
                'message' => 'Sin datos de nómina procesados para este periodo. Ejecuta primero "Cargar registros" para poder ver las personas sin sucursal asignada.',
            ]);
        }

        // Raw per-employee-per-source rows (employees that have no branch assignment)
        $rawItems = DB::table('fact_noi_movements as n')
            ->leftJoin('employee_branch_assignments as eba', function ($j) use ($period, $dataIds) {
                $j->on('eba.employee_id', '=', 'n.employee_id')
                  ->whereIn('eba.period_id', array_merge([$period->id], $dataIds));
            })
            ->leftJoin('employees as emp', 'n.employee_id', '=', 'emp.id')
            ->join('report_uploads as ru', 'n.report_upload_id', '=', 'ru.id')
            ->join('data_sources as ds', 'ru.data_source_id', '=', 'ds.id')
            ->whereIn('n.period_id', $dataIds)
            ->whereNotNull('n.employee_id')
            ->whereNull('eba.branch_id')
            ->selectRaw('
                n.employee_id,
                COALESCE(emp.full_name, CONCAT("Emp #", n.employee_id)) AS nombre,
                COALESCE(emp.normalized_name, "") AS normalized_name,
                COALESCE(emp.employee_code, NULL) AS employee_code,
                ds.code AS fuente,
                COUNT(DISTINCT n.id) AS movimientos,
                SUM(n.amount) AS monto
            ')
            ->groupBy('n.employee_id', 'emp.full_name', 'emp.normalized_name', 'emp.employee_code', 'ds.id', 'ds.code')
            ->orderByDesc('monto')
            ->limit(500)
            ->get();

        // Group by normalized_name so NOI regular + NOI fiscal rows for the same person merge into one row
        $grouped = $rawItems->groupBy(function ($row) {
            return ($row->normalized_name !== '') ? $row->normalized_name : $row->nombre;
        });

        // Build one aggregated item per unique person
        $items = $grouped->map(function ($group) {
            $best        = $group->sortByDesc('monto')->first();
            $employeeIds = $group->pluck('employee_id')->unique()->map(fn ($id) => (int) $id)->values()->all();
            $fuentes     = $group->pluck('fuente')->unique()->sort()->values()->all();

            return (object) [
                'employee_ids'    => $employeeIds,
                'employee_id'     => (int) $best->employee_id,
                'nombre'          => (string) $best->nombre,
                'normalized_name' => (string) $best->normalized_name,
                'employee_code'   => $best->employee_code,
                'fuentes'         => $fuentes,
                'movimientos'     => (int) $group->sum('movimientos'),
                'monto'           => (float) $group->sum('monto'),
            ];
        })->sortByDesc('monto')->values();

        // ── Pre-load data for diagnosis ──────────────────────────────────
        $allEmployeeIds = $items->flatMap(fn ($item) => $item->employee_ids)->unique()->values()->all();

        $allEmployees = \App\Models\Employee::query()
            ->whereNotNull('normalized_name')
            ->get(['id', 'full_name', 'normalized_name']);

        $rawMovements = DB::table('fact_noi_movements as n')
            ->join('report_uploads as ru', 'n.report_upload_id', '=', 'ru.id')
            ->join('data_sources as ds', 'ru.data_source_id', '=', 'ds.id')
            ->whereIn('n.period_id', $dataIds)
            ->whereIn('n.employee_id', $allEmployeeIds)
            ->select('n.employee_id', 'n.movement_date', 'n.concept', 'n.amount', 'n.raw_payload', 'ds.code as source')
            ->orderByDesc('n.amount')
            ->get()
            ->groupBy('employee_id');

        $historicalBranches = DB::table('employee_branch_assignments as eba')
            ->join('branches as b', 'eba.branch_id', '=', 'b.id')
            ->whereIn('eba.employee_id', $allEmployeeIds)
            ->whereNotNull('eba.branch_id')
            ->orderByDesc('eba.period_id')
            ->select('eba.employee_id', 'b.name as branch_name')
            ->get()
            ->unique('employee_id')
            ->keyBy('employee_id');

        /** @var \App\Services\PersonIdentityResolverService $resolver */
        $resolver = app(\App\Services\PersonIdentityResolverService::class);

        $items = $items->map(function ($item) use ($resolver, $allEmployees, $rawMovements, $historicalBranches, $dataIds) {
            // Merge sample movements across all employee_ids in the group
            $sampleMovs = collect(array_merge(
                ...array_map(fn ($eid) => ($rawMovements[(int) $eid] ?? collect())->all(), $item->employee_ids)
            ));

            $diagnosis = $resolver->buildResolutionTrace(
                employeeId:       (int) $item->employee_id,
                fullName:         (string) $item->nombre,
                allEmployees:     $allEmployees,
                sampleMovs:       $sampleMovs,
                employeeCode:     $item->employee_code ?? null,
                historicalBranch: $historicalBranches[(int) $item->employee_id]->branch_name ?? null,
                dataIds:          $dataIds,
            );
            $item->diagnosis = $diagnosis;

            $bestMatch = $diagnosis['candidate_matches'][0] ?? null;
            $isGrouped = count($item->employee_ids) > 1;
            // Exact same normalized name = confirmed same person (from NOI regular + NOI fiscal or duplicates).
            // Always go directly to branch selector — never ask "¿Es la misma persona?".
            if ($bestMatch && $bestMatch['score'] >= 100.0) {
                $item->resolution_type = $bestMatch['branch'] ? 'exact_name_has_branch' : 'exact_name_no_branch';
            } elseif ($bestMatch && $bestMatch['score'] >= 80.0) {
                $item->resolution_type = $bestMatch['branch'] ? 'fuzzy_match_has_branch' : 'fuzzy_match_no_branch';
            } elseif ($bestMatch && $bestMatch['score'] >= 60.0) {
                $item->resolution_type = 'possible_match';
            } else {
                $item->resolution_type = 'needs_branch';
            }
            $item->best_match = $bestMatch;

            return $item;
        });

        return response()->json(['items' => $items->values()]);
    }

    /**
     * Confirm that two employee records are the same person.
     * Creates alias records and inherits branch from the target if available.
     * Optionally accepts a canonical_name to update both employees' display name.
     */
    public function confirmarCoincidencia(Period $period, \Illuminate\Http\Request $request): \Illuminate\Http\JsonResponse
    {
        $validated = $request->validate([
            'employee_id'        => ['required', 'integer', 'exists:employees,id'],
            'target_employee_id' => ['required', 'integer', 'exists:employees,id', 'different:employee_id'],
            'branch_id'          => ['nullable', 'integer', 'exists:branches,id'],
            'canonical_name'     => ['nullable', 'string', 'max:255'],
        ]);

        try {
            $allPeriods = \App\Models\Period::all();
            $weeklyIds  = $period->resolveBaseWeeklyIds($allPeriods);
            $dataIds    = array_values(array_unique(array_merge(
                empty($weeklyIds) ? [] : $weeklyIds,
                [$period->id]
            )));

            $emp    = \App\Models\Employee::findOrFail($validated['employee_id']);
            $target = \App\Models\Employee::findOrFail($validated['target_employee_id']);

            /** @var \App\Services\PersonIdentityResolverService $resolver */
            $resolver = app(\App\Services\PersonIdentityResolverService::class);

            // Apply canonical name if provided — update both employees
            $canonicalName = trim($validated['canonical_name'] ?? '');
            if ($canonicalName !== '') {
                $canonicalNorm = $resolver->normalizePersonName($canonicalName);
                if ($resolver->normalizePersonName($emp->full_name) !== $canonicalNorm) {
                    $emp->update(['full_name' => $canonicalName, 'normalized_name' => $canonicalNorm]);
                }
                if ($resolver->normalizePersonName($target->full_name) !== $canonicalNorm) {
                    $target->update(['full_name' => $canonicalName, 'normalized_name' => $canonicalNorm]);
                }
                $emp->refresh();
                $target->refresh();
            }

            // Save alias in both directions (if names differ after canonical update)
            $normEmp    = $resolver->normalizePersonName($emp->full_name);
            $normTarget = $resolver->normalizePersonName($target->full_name);
            if ($normEmp !== $normTarget) {
                \App\Models\EmployeeAlias::query()->updateOrCreate(
                    ['employee_id' => $target->id, 'normalized_alias' => $normEmp],
                    ['alias_name' => $emp->full_name, 'source' => 'confirmed_match', 'confidence' => 1.00, 'created_by' => auth()->id()]
                );
                \App\Models\EmployeeAlias::query()->updateOrCreate(
                    ['employee_id' => $emp->id, 'normalized_alias' => $normTarget],
                    ['alias_name' => $target->full_name, 'source' => 'confirmed_match', 'confidence' => 1.00, 'created_by' => auth()->id()]
                );
            }

            // Resolve which branch to use
            $branchId = $validated['branch_id']
                ?? $resolver->resolveBranchFromExistingAssignments($target->id)
                ?? $resolver->resolveBranchFromCanonicalEmployee($emp);

            if ($branchId) {
                \App\Models\EmployeeBranchAssignment::query()->updateOrCreate(
                    ['period_id' => $period->id, 'employee_id' => $emp->id],
                    [
                        'branch_id'           => $branchId,
                        'source_type'         => 'manual',
                        'source_reference'    => "Confirmado como misma persona que #{$target->id} — {$target->full_name}",
                        'match_type'          => 'manual',
                        'confidence'          => 1.00,
                        'was_manual_reviewed' => true,
                        'notes'               => "Unificado manualmente. Alias confirmado con \"{$target->full_name}\".",
                    ]
                );
            }

            // Lightweight refreshes — no full radiography needed
            $this->refreshEmpleadosSinSucursalIncident($period, $dataIds);
            $this->refreshCoincidenciasIncident($period, $dataIds);

            return response()->json(['ok' => true, 'branch_assigned' => (bool) $branchId]);

        } catch (\Throwable $e) {
            \Illuminate\Support\Facades\Log::error('confirmarCoincidencia error', [
                'period_id'   => $period->id,
                'payload'     => $request->all(),
                'error'       => $e->getMessage(),
                'file'        => $e->getFile() . ':' . $e->getLine(),
            ]);
            return response()->json([
                'ok'      => false,
                'message' => 'No se pudo confirmar la coincidencia: ' . $e->getMessage(),
                'error'   => app()->isLocal() ? $e->getMessage() : null,
            ], 500);
        }
    }

    private function refreshEmpleadosSinSucursalIncident(Period $period, array $dataIds): void
    {
        $summary = PeriodSummary::query()->where('period_id', $period->id)->first();
        if (!$summary) return;

        // Count raw employee_id records without branch
        $sinSucursal = DB::table('fact_noi_movements as n')
            ->leftJoin('employee_branch_assignments as eba', function ($j) use ($period, $dataIds) {
                $j->on('eba.employee_id', '=', 'n.employee_id')
                  ->whereIn('eba.period_id', array_merge([$period->id], $dataIds));
            })
            ->whereIn('n.period_id', $dataIds)
            ->whereNotNull('n.employee_id')
            ->whereNull('eba.branch_id')
            ->distinct('n.employee_id')
            ->count('n.employee_id');

        $existing = PeriodIncident::query()
            ->where('period_summary_id', $summary->id)
            ->where('type', 'empleados_sin_sucursal')
            ->first();

        if ($sinSucursal === 0) {
            $existing?->delete();
            return;
        }

        $sinSucursalMonto = (float) DB::table('fact_noi_movements as n')
            ->leftJoin('employee_branch_assignments as eba', function ($j) use ($period, $dataIds) {
                $j->on('eba.employee_id', '=', 'n.employee_id')
                  ->whereIn('eba.period_id', array_merge([$period->id], $dataIds));
            })
            ->whereIn('n.period_id', $dataIds)
            ->whereNotNull('n.employee_id')
            ->whereNull('eba.branch_id')
            ->sum('n.amount');

        // Count unique persons (grouped by normalized_name) — for UI display
        $uniquePersons = (int) DB::table('fact_noi_movements as n')
            ->leftJoin('employee_branch_assignments as eba', function ($j) use ($period, $dataIds) {
                $j->on('eba.employee_id', '=', 'n.employee_id')
                  ->whereIn('eba.period_id', array_merge([$period->id], $dataIds));
            })
            ->leftJoin('employees as emp', 'n.employee_id', '=', 'emp.id')
            ->whereIn('n.period_id', $dataIds)
            ->whereNotNull('n.employee_id')
            ->whereNull('eba.branch_id')
            ->whereNotNull('emp.normalized_name')
            ->distinct('emp.normalized_name')
            ->count('emp.normalized_name');

        // If some employees have no normalized_name, fall back to raw count
        if ($uniquePersons === 0) $uniquePersons = $sinSucursal;

        $severity = abs($sinSucursalMonto) > 0 ? 'high' : 'warning';
        $ctx = [
            'count'               => $sinSucursal,
            'unique_persons_count'=> $uniquePersons,
            'monto'               => $sinSucursalMonto,
        ];

        if ($existing) {
            $existing->update([
                'severity' => $severity,
                'message'  => "{$sinSucursal} empleado(s) del NOI no tienen sucursal asignada. Sus datos no aparecen en reportes por sucursal."
                    . ($severity === 'high' ? ' Impacto monetario: $' . number_format(abs($sinSucursalMonto), 2) : ''),
                'context'  => $ctx,
            ]);
        } else {
            PeriodIncident::query()->create([
                'period_summary_id' => $summary->id,
                'type'     => 'empleados_sin_sucursal',
                'severity' => $severity,
                'message'  => "{$sinSucursal} empleado(s) del NOI no tienen sucursal asignada. Sus datos no aparecen en reportes por sucursal."
                    . ($severity === 'high' ? ' Impacto monetario: $' . number_format(abs($sinSucursalMonto), 2) : ''),
                'context'  => $ctx,
            ]);
        }
    }

    /**
     * Lightweight refresh of the posibles_coincidencias_persona incident.
     * Re-runs detection (excludes rejected/aliased pairs) and updates or creates/deletes the incident.
     */
    private function refreshCoincidenciasIncident(Period $period, array $dataIds): void
    {
        $summary = PeriodSummary::query()->where('period_id', $period->id)->first();
        if (!$summary) return;

        /** @var \App\Services\PeriodRadiographyService $svc */
        $svc           = app(\App\Services\PeriodRadiographyService::class);
        $coincidencias = $svc->detectCoincidencias($dataIds);

        $existing = PeriodIncident::query()
            ->where('period_summary_id', $summary->id)
            ->where('type', 'posibles_coincidencias_persona')
            ->first();

        if (empty($coincidencias)) {
            $existing?->delete();
            return;
        }

        $coincidenciaIds = array_unique(array_merge(
            array_column($coincidencias, 'a_id'),
            array_column($coincidencias, 'b_id'),
        ));
        $monetaryAmount = (float) DB::table('fact_noi_movements')
            ->whereIn('period_id', $dataIds)
            ->whereIn('employee_id', $coincidenciaIds)
            ->sum('amount');
        $hasMoney = abs($monetaryAmount) > 0;

        $data = [
            'type'     => 'posibles_coincidencias_persona',
            'severity' => $hasMoney ? 'high' : 'warning',
            'message'  => count($coincidencias) . ' posible(s) coincidencia(s) de persona detectada(s). Verifica si se trata de la misma persona escrita de forma diferente.'
                . ($hasMoney ? ' Tienen impacto monetario: $' . number_format(abs($monetaryAmount), 2) . '.' : ''),
            'context'  => [
                'count'   => count($coincidencias),
                'monto'   => $monetaryAmount,
                'samples' => array_slice($coincidencias, 0, 10),
            ],
        ];

        if ($existing) {
            $existing->update($data);
        } else {
            PeriodIncident::query()->create(['period_summary_id' => $summary->id, ...$data]);
        }
    }

    /**
     * Permanently discard a coincidencia pair so it won't reappear in future checks.
     * Saves an employee_match_rejections record and refreshes the incident.
     */
    public function descartarCoincidencia(Period $period, \Illuminate\Http\Request $request): \Illuminate\Http\JsonResponse
    {
        $validated = $request->validate([
            'employee_id_a' => ['required', 'integer', 'exists:employees,id'],
            'employee_id_b' => ['required', 'integer', 'exists:employees,id', 'different:employee_id_a'],
        ]);

        $pairKey = \App\Models\EmployeeMatchRejection::pairKey(
            (int) $validated['employee_id_a'],
            (int) $validated['employee_id_b']
        );

        \App\Models\EmployeeMatchRejection::query()->updateOrCreate(
            ['pair_key' => $pairKey],
            [
                'employee_id_a' => min((int) $validated['employee_id_a'], (int) $validated['employee_id_b']),
                'employee_id_b' => max((int) $validated['employee_id_a'], (int) $validated['employee_id_b']),
                'period_id'     => $period->id,
                'reason'        => 'Descartado manualmente — no son la misma persona.',
                'created_by'    => auth()->id(),
            ]
        );

        $allPeriods = Period::all();
        $weeklyIds  = $period->resolveBaseWeeklyIds($allPeriods);
        $dataIds    = array_values(array_unique(array_merge(
            empty($weeklyIds) ? [] : $weeklyIds,
            [$period->id]
        )));
        $this->refreshCoincidenciasIncident($period, $dataIds);

        return response()->json(['ok' => true]);
    }

    public function resolvePendingLocation(Period $period, \Illuminate\Http\Request $request): \Illuminate\Http\RedirectResponse
    {
        $validated = $request->validate([
            'incident_id' => ['required', 'integer'],
            'action'      => ['required', 'in:map_to_branch,exclude,mark_corporate,mark_closed'],
            'branch_id'   => ['nullable', 'integer', 'exists:branches,id'],
        ]);

        $incident = PeriodIncident::findOrFail($validated['incident_id']);
        abort_unless($incident->periodSummary?->period_id === $period->id, 404);

        $actionLabel = match ($validated['action']) {
            'map_to_branch'  => 'Mapeada a sucursal',
            'exclude'        => 'Excluida del reporte',
            'mark_corporate' => 'Marcada como Corporativo',
            'mark_closed'    => 'Marcada como sucursal cerrada',
        };

        $branchName = null;
        if ($validated['branch_id']) {
            $branchName = \App\Models\Branch::find($validated['branch_id'])?->name;
        }

        $incident->update([
            'severity' => 'resolved',
            'context'  => array_merge($incident->context ?? [], [
                'resolved_action' => $validated['action'],
                'resolved_branch' => $branchName,
                'resolved_by'     => auth()->id(),
                'resolved_at'     => now()->toDateTimeString(),
            ]),
        ]);

        return back()->with('success', "Ubicación resuelta: {$actionLabel}.");
    }

    public function resolveIncident(Period $period, PeriodIncident $incident, Request $request): RedirectResponse
    {
        abort_unless($incident->periodSummary?->period_id === $period->id, 404);

        $incident->update([
            'severity' => 'resolved',
            'context'  => array_merge($incident->context ?? [], [
                'resolved_by'      => auth()->id(),
                'resolved_at'      => now()->toDateTimeString(),
                'resolution_note'  => (string) $request->input('resolution_note', 'Resuelta manualmente.'),
            ]),
        ]);

        return back()->with('success', 'Incidencia resuelta correctamente.');
    }

    public function generateRadiography(Period $period, Request $request): RedirectResponse
    {
        $allPeriods   = Period::query()->get();
        $coveredWeeks = $this->resolveCoveredWeeks($period, $allPeriods);
        $uploads      = $this->resolveUploadsForWeeks($coveredWeeks);
        $summary      = PeriodSummary::query()->where('period_id', $period->id)->with('incidents')->first();
        $latestRun    = PeriodRadiographyRun::query()->where('period_id', $period->id)->latest('id')->first();

        $bdSourceCodes     = DataSource::query()->where('is_active', true)->where('is_required_for_bd', true)->pluck('code')->values()->all();
        $reportSourceCodes = DataSource::query()->where('is_active', true)->where('is_required_for_report', true)->pluck('code')->values()->all();

        $workflow = $this->resolveWorkflowState($uploads, $summary, $latestRun, $period->isCompound(), null, $bdSourceCodes, $reportSourceCodes);

        if (!$workflow['can_generate_radiography']) {
            return back()->with('error', implode(' ', $workflow['blocking_reasons']) ?: 'No se puede generar la Radiografía todavía.');
        }

        $config = $request->input('config', []);
        $scope  = $config['scope'] ?? 'general';
        $type   = ($config['report_type'] ?? 'simple') === 'simple' ? 'Radiografía simple' : 'Reporte comparativo';

        $run = PeriodRadiographyRun::query()->create([
            'period_id'  => $period->id,
            'status'     => 'queued',
            'queued_at'  => now(),
            'created_by' => auth()->id(),
            'log'        => "Radiografía en cola. Se generará un {$type} con alcance {$scope}.",
            'metadata'   => ['config' => $config, 'progress_percent' => 0, 'current_step' => 'En cola'],
        ]);

        GenerateRadiographyJob::dispatch($period->id, auth()->id(), $run->id, $config);

        return back()->with('success', 'La Radiografía se está generando en segundo plano. Recibirás un correo cuando esté lista.');
    }

    /**
     * JSON endpoint: current progress of the most recent radiography generation run.
     * Polled every 3 s by the GenerateReportStep Vue component.
     */
    public function generationProgress(Period $period): \Illuminate\Http\JsonResponse
    {
        $run = PeriodRadiographyRun::query()
            ->where('period_id', $period->id)
            ->latest('id')
            ->first();

        if (!$run) {
            return response()->json(['status' => null]);
        }

        $status   = $run->status;
        $isQueued = $status === 'queued';
        $running  = in_array($status, ['queued', 'running'], true);

        $elapsedSeconds = null;
        $stuckWarning   = false;

        if ($running) {
            $ref = $isQueued
                ? ($run->queued_at ?? $run->created_at)
                : ($run->started_at ?? $run->queued_at ?? $run->created_at);
            $elapsedSeconds = $ref ? max(0, (int) now()->diffInSeconds($ref)) : null;
            $stuckWarning   = $elapsedSeconds !== null && (
                ($isQueued && $elapsedSeconds >= 300) ||
                (!$isQueued && $elapsedSeconds >= 1800)
            );
        } elseif ($run->started_at && $run->finished_at) {
            $elapsedSeconds = max(0, (int) $run->started_at->diffInSeconds($run->finished_at));
        }

        $excelUrl = $run->output_excel_path
            ? route('reportes-mensuales.export-radiography', $period->id)
            : null;
        $pdfUrl = $run->output_pdf_path
            ? route('reportes-mensuales.export-radiography-pdf', $period->id)
            : null;

        return response()->json([
            'status'          => $status,
            'run_id'          => $run->id,
            'log'             => $run->log ? mb_strimwidth($run->log, 0, 300) : null,
            'error_message'   => $run->error_message ? mb_strimwidth($run->error_message, 0, 300) : null,
            'queued_at'       => optional($run->queued_at ?? $run->created_at)->format('d/m/Y H:i'),
            'started_at'      => $isQueued ? null : optional($run->started_at)->format('d/m/Y H:i'),
            'finished_at'     => optional($run->finished_at)->format('d/m/Y H:i'),
            'elapsed_seconds' => $elapsedSeconds,
            'stuck_warning'   => $stuckWarning,
            'metadata'        => $run->metadata,
            'excel_url'       => $excelUrl,
            'pdf_url'         => $pdfUrl,
            'can_process_now' => !app()->isProduction() && $isQueued,
        ]);
    }

    /**
     * Cancel an active (queued or running) radiography generation.
     */
    public function cancelGeneration(Period $period): RedirectResponse
    {
        $run = PeriodRadiographyRun::query()
            ->where('period_id', $period->id)
            ->whereIn('status', ['queued', 'running'])
            ->latest('id')
            ->first();

        if (!$run) {
            return back()->with('error', 'No hay una generación activa para cancelar en este periodo.');
        }

        $cancelledBy = auth()->user()?->name ?? 'usuario';
        $run->update([
            'status'        => 'cancelled',
            'finished_at'   => now(),
            'cancelled_at'  => now(),
            'cancelled_by'  => auth()->id(),
            'log'           => "Generación cancelada por {$cancelledBy}.",
            'error_message' => 'Cancelado manualmente.',
            'metadata'      => array_merge(is_array($run->metadata) ? $run->metadata : [], [
                'current_step' => 'Cancelado',
            ]),
        ]);

        return back()->with('success', 'La generación fue cancelada. Puedes reintentarla cuando estés listo.');
    }

    /**
     * Run the generation job synchronously (local/debug only).
     */
    public function processGenerationNow(Period $period): RedirectResponse
    {
        abort_if(app()->isProduction(), 403, 'Solo disponible en entorno local/debug.');

        $run = PeriodRadiographyRun::query()
            ->where('period_id', $period->id)
            ->where('status', 'queued')
            ->latest('id')
            ->first();

        if (!$run) {
            return back()->with('error', 'No hay una generación en cola para procesar.');
        }

        @set_time_limit(0);
        @ini_set('memory_limit', '1024M');

        try {
            $config = is_array($run->metadata) ? ($run->metadata['config'] ?? []) : [];
            $job = new GenerateRadiographyJob($period->id, auth()->id(), $run->id, $config);
            app()->call([$job, 'handle']);
            return back()->with('success', 'Generación completada. Descarga Excel y PDF desde el paso de reporte.');
        } catch (\Throwable $e) {
            return back()->with('info', 'La generación terminó con error. Revisa el detalle en la etapa de generar reporte.');
        }
    }

    public function analyze(ReportUpload $reportUpload): RedirectResponse
    {
        $sourceCode = $reportUpload->dataSource?->code ?? '';
        $sourceName = $reportUpload->dataSource?->name ?? 'La fuente';

        $bdSourceCodes = DataSource::query()->where('is_active', true)->where('is_required_for_bd', true)->pluck('code')->values()->all();
        $isBdSource    = in_array($sourceCode, $bdSourceCodes, true);

        $summary = PeriodSummary::query()
            ->where('period_id', $reportUpload->period_id)
            ->whereNull('invalidated_at')
            ->first();

        if ($summary && $isBdSource) {
            $summary->update([
                'invalidated_at'     => now(),
                'invalidated_by'     => auth()->id(),
                'invalidated_reason' => "Fuente de BD reprocesada: {$sourceName}. La actualización de BD debe ejecutarse nuevamente.",
            ]);
        } elseif ($summary && !$isBdSource && $summary->status === 'generated') {
            $summary->update([
                'status'             => 'database_updated',
                'invalidated_reason' => "Fuente reprocesada: {$sourceName}. Re-genera la Radiografía para reflejar los cambios.",
            ]);
        }

        ReprocessReportUploadJob::dispatch($reportUpload->id, auth()->id());

        return back()->with('success', "'{$sourceName}' fue enviado a reprocesamiento en cola. Recibirás un correo cuando termine.");
    }

    public function reprocessAll(Period $period): RedirectResponse
    {
        $existing = PeriodReprocessRun::query()
            ->where('period_id', $period->id)
            ->whereIn('status', ['queued', 'running'])
            ->first();

        if ($existing) {
            return back()->with('error', 'Ya hay un reprocesamiento en curso para este periodo. Espera a que termine.');
        }

        $summary = PeriodSummary::query()
            ->where('period_id', $period->id)
            ->whereNull('invalidated_at')
            ->first();

        if ($summary) {
            $summary->update([
                'invalidated_at'     => now(),
                'invalidated_by'     => auth()->id(),
                'invalidated_reason' => 'Todo el periodo fue enviado a reprocesamiento.',
            ]);
        }

        $allPeriods      = Period::query()->get();
        $coveredWeeks    = $this->resolveCoveredWeeks($period, $allPeriods);
        $coveredPeriodIds = $coveredWeeks->pluck('id')->map(fn ($id) => (int) $id)->values()->all();

        $run = PeriodReprocessRun::query()->create([
            'period_id'  => $period->id,
            'created_by' => auth()->id(),
            'status'     => 'queued',
            'log'        => 'Reprocesamiento completo del periodo en cola.',
            'metadata'   => ['progress' => 0],
            'started_at' => now(),
        ]);

        ReprocessPeriodUploadsJob::dispatch($period->id, $run->id, $coveredPeriodIds, auth()->id());

        return back()->with('success', 'El reprocesamiento completo fue enviado a cola. Recibirás un correo cuando termine.');
    }

    public function cancelDatabaseUpdate(Period $period): RedirectResponse
    {
        $run = PeriodDatabaseUpdateRun::query()
            ->where('period_id', $period->id)
            ->whereIn('status', ['queued', 'running'])
            ->latest('id')
            ->first();

        if (!$run) {
            return back()->with('error', 'No hay un proceso activo para cancelar en este periodo.');
        }

        // Remove the job from the queue so it doesn't run after being cancelled
        $this->deleteJobForRun($run->id);

        $cancelledBy = auth()->user()?->name ?? 'usuario';
        $run->update([
            'status'        => 'cancelled',
            'finished_at'   => now(),
            'log'           => "Carga cancelada por {$cancelledBy}.",
            'error_message' => 'Cancelado manualmente.',
        ]);

        return back()->with('success', 'El proceso fue cancelado. Puedes reintentarlo cuando estés listo.');
    }

    public function clearStuckDatabaseUpdate(Period $period): RedirectResponse
    {
        $run = PeriodDatabaseUpdateRun::query()
            ->where('period_id', $period->id)
            ->whereIn('status', ['queued', 'running'])
            ->latest('id')
            ->first();

        if (!$run) {
            return back()->with('error', 'No hay un proceso en estado atascado para este periodo.');
        }

        $this->deleteJobForRun($run->id);

        $run->update([
            'status'        => 'cancelled',
            'finished_at'   => now(),
            'log'           => 'Estado limpiado manualmente por ' . (auth()->user()?->name ?? 'usuario') . '.',
            'error_message' => 'Limpiado manualmente (proceso atascado).',
        ]);

        return back()->with('success', 'Estado limpiado. Ya puedes volver a iniciar la carga.');
    }

    public function loadProgressStatus(Period $period): \Illuminate\Http\JsonResponse
    {
        $dbRun = PeriodDatabaseUpdateRun::query()
            ->where('period_id', $period->id)
            ->latest('id')
            ->first();

        if (!$dbRun) {
            return response()->json(['status' => null]);
        }

        $status   = $dbRun->status;
        $isQueued = $status === 'queued';
        $running  = in_array($status, ['queued', 'running'], true);

        $elapsedSeconds = null;
        $stuckWarning   = false;
        $jobInQueue     = false;
        $orphaned       = false;

        if ($running) {
            $ref = $isQueued
                ? ($dbRun->queued_at ?? $dbRun->created_at)
                : ($dbRun->started_at ?? $dbRun->queued_at ?? $dbRun->created_at);
            $elapsedSeconds = $ref ? max(0, (int) now()->diffInSeconds($ref)) : null;
            $stuckWarning   = $elapsedSeconds !== null && (
                ($isQueued && $elapsedSeconds >= 300) ||
                (!$isQueued && $elapsedSeconds >= 1800)
            );

            if ($isQueued) {
                $jobInQueue = $this->jobExistsForRun($dbRun->id);
                $orphaned   = !$jobInQueue;
            }
        } elseif ($dbRun->started_at && $dbRun->finished_at) {
            $elapsedSeconds = max(0, (int) $dbRun->started_at->diffInSeconds($dbRun->finished_at));
        }

        return response()->json([
            'status'          => $status,
            'log'             => $dbRun->log ? mb_strimwidth($dbRun->log, 0, 300) : null,
            'error_message'   => $dbRun->error_message ? mb_strimwidth($dbRun->error_message, 0, 300) : null,
            'queued_at'       => optional($dbRun->queued_at ?? $dbRun->created_at)->format('d/m/Y H:i'),
            'started_at'      => $isQueued ? null : optional($dbRun->started_at)->format('d/m/Y H:i'),
            'finished_at'     => optional($dbRun->finished_at)->format('d/m/Y H:i'),
            'elapsed_seconds' => $elapsedSeconds,
            'stuck_warning'   => $stuckWarning,
            'metadata'        => $dbRun->metadata,
            'job_in_queue'    => $jobInQueue,
            'orphaned'        => $orphaned,
            'can_process_now' => !app()->isProduction() && $isQueued,
        ]);
    }

    public function processNow(Period $period): RedirectResponse
    {
        abort_if(app()->isProduction(), 403, 'Solo disponible en entorno local/debug.');

        $run = PeriodDatabaseUpdateRun::query()
            ->where('period_id', $period->id)
            ->where('status', 'queued')
            ->latest('id')
            ->first();

        if (!$run) {
            return back()->with('error', 'No hay un run en cola para procesar.');
        }

        // Remove from jobs table to prevent double-processing if worker starts later
        $this->deleteJobForRun($run->id);

        @set_time_limit(0);
        @ini_set('memory_limit', '512M');

        try {
            $job = new UpdatePeriodDatabaseJob($period->id, $run->id, auth()->id());
            app()->call([$job, 'handle']);
            return back()->with('success', 'Proceso completado. Revisa el resultado en esta misma página.');
        } catch (\Throwable $e) {
            // Job already marked run as failed and sent email before re-throwing
            return back()->with('info', 'El proceso terminó con error. Revisa el detalle en la etapa de carga.');
        }
    }

    public function requeueRun(Period $period): RedirectResponse
    {
        $run = PeriodDatabaseUpdateRun::query()
            ->where('period_id', $period->id)
            ->where('status', 'queued')
            ->latest('id')
            ->first();

        if (!$run) {
            return back()->with('error', 'No hay un run en cola para reencolar.');
        }

        if ($this->jobExistsForRun($run->id)) {
            return back()->with('info', 'El job ya existe en la cola. Inicia el worker para procesarlo.');
        }

        $run->update([
            'queued_at' => now(),
            'log'       => 'Job reencolado. Esperando worker.',
        ]);

        UpdatePeriodDatabaseJob::dispatch($period->id, $run->id, auth()->id());

        return back()->with('success', 'Job reencolado. Inicia el worker para procesarlo.');
    }

    private function jobExistsForRun(int $runId): bool
    {
        return DB::table('jobs')
            ->where('payload', 'LIKE', '%UpdatePeriodDatabaseJob%')
            ->where('payload', 'LIKE', '%runId%i:' . $runId . ';%')
            ->exists();
    }

    private function deleteJobForRun(int $runId): void
    {
        DB::table('jobs')
            ->where('payload', 'LIKE', '%UpdatePeriodDatabaseJob%')
            ->where('payload', 'LIKE', '%runId%i:' . $runId . ';%')
            ->delete();
    }

    // ── Helpers privados ──────────────────────────────────────────────

    private function previewPayload(?Period $period): array
    {
        if (!$period) {
            return ['metrics' => [], 'employees' => []];
        }

        $summary = MonthlyEmployeeSummary::query()
            ->where('period_id', $period->id)
            ->selectRaw('COUNT(*) as total_empleados')
            ->selectRaw('SUM(total_expenses) as gasto_total')
            ->selectRaw('SUM(net_amount) as neto_total')
            ->selectRaw('SUM(total_payments) as pagos_total')
            ->first();

        return [
            'metrics' => [
                'total_empleados' => (int) ($summary->total_empleados ?? 0),
                'gasto_total'     => (float) ($summary->gasto_total ?? 0),
                'neto_total'      => (float) ($summary->neto_total ?? 0),
                'pagos_total'     => (float) ($summary->pagos_total ?? 0),
            ],
            'employees' => MonthlyEmployeeSummary::query()
                ->with(['employee:id,full_name', 'branch:id,name'])
                ->where('period_id', $period->id)
                ->limit(50)
                ->get()
                ->map(fn (MonthlyEmployeeSummary $row) => [
                    'id'             => $row->id,
                    'employee_name'  => $row->employee?->full_name ?? 'Sin empleado',
                    'branch_name'    => $row->branch?->name,
                    'total_payments' => (float) $row->total_payments,
                    'total_expenses' => (float) $row->total_expenses,
                    'net_amount'     => (float) $row->net_amount,
                ])->values(),
        ];
    }

    // Resolución recursiva: retorna los periodos SEMANALES que componen el periodo dado.
    // Usa component_period_ids cuando existe; hace fallback por fecha en caso contrario.
    private function resolveCoveredWeeks(Period $period, Collection $allPeriods): Collection
    {
        if ($period->isBase()) {
            return $allPeriods->where('id', $period->id)->values();
        }

        $weeklyIds = $period->resolveBaseWeeklyIds($allPeriods);

        return $allPeriods->whereIn('id', $weeklyIds)->where('type', 'weekly')->values();
    }

    private function resolveUploadsForWeeks(Collection $coveredWeeks): Collection
    {
        if ($coveredWeeks->isEmpty()) return collect();

        $weekIds = $coveredWeeks->pluck('id')->map(fn ($id) => (int) $id)->values()->all();

        return ReportUpload::query()
            ->with('dataSource:id,code,name')
            ->get()
            ->filter(function (ReportUpload $upload) use ($weekIds) {
                $coveredIds = collect($upload->covered_period_ids ?? [])
                    ->map(fn ($id) => (int) $id);

                if ($coveredIds->isNotEmpty()) {
                    return $coveredIds->intersect($weekIds)->isNotEmpty();
                }

                return in_array((int) $upload->period_id, $weekIds, true);
            })
            ->sortByDesc('created_at')
            ->values();
    }

    private function resolveWorkflowState(
        Collection            $uploads,
        ?PeriodSummary        $summary,
        ?PeriodRadiographyRun $run          = null,
        bool                  $compoundPeriod = false,
        ?PeriodDatabaseUpdateRun $dbRun     = null,
        array                 $bdSourceCodes = [],
        array                 $reportSourceCodes = [],
    ): array {
        $sourceCodes = $uploads->pluck('dataSource.code')->filter()->unique()->values();

        $missingDb = collect($bdSourceCodes)
            ->filter(fn ($code) => !$sourceCodes->contains($code))
            ->values()
            ->all();

        $missingRadiography = collect($reportSourceCodes)
            ->filter(fn ($code) => !$sourceCodes->contains($code))
            ->values()
            ->all();

        $failedDb = collect($bdSourceCodes)->filter(function ($code) use ($uploads) {
            $upload = $uploads->first(fn ($item) => $item->dataSource?->code === $code);
            return $upload && (string) ($upload->status?->value ?? $upload->status) === 'failed';
        })->values()->all();

        $unprocessedRadiography = collect($reportSourceCodes)->filter(function ($code) use ($uploads) {
            $upload = $uploads->first(fn ($item) => $item->dataSource?->code === $code);
            if (!$upload) return false;
            return (string) ($upload->status?->value ?? $upload->status) !== 'processed';
        })->values()->all();

        $pendingCritical = (int) ($summary?->incidents()->where('severity', 'high')->count() ?? 0);

        // ── Stale-upload detection ────────────────────────────────────────────
        // The BD state is stale (period_summary says 'database_updated' but data is gone) when:
        //   - The last DB_UPDATE_RUN completed successfully
        //   - AND at least one BD-required upload is NOT processed
        //
        // Note: the DB_UPDATE_RUN does NOT necessarily mark uploads as 'processed' itself —
        // that happens via separate reimport flows. So the simple fact that a BD-required upload
        // is pending while a successful run exists means there's a discrepancy.
        $staleUploads    = [];
        $staleUploadInfo = [];
        if ($dbRun && $dbRun->status === 'success' && $dbRun->finished_at && $summary) {
            // Only flag as stale if summary was created from this run (status still 'database_updated')
            // AND fact data is absent for the BD-required sources
            $summaryIsFromRun = in_array($summary->status, ['database_updated', 'generated'], true)
                && !$summary->invalidated_at;

            if ($summaryIsFromRun) {
                foreach ($bdSourceCodes as $code) {
                    $upload = $uploads->first(fn ($item) => ($item->dataSource?->code ?? '') === $code);
                    if (!$upload) continue;
                    $status = (string) ($upload->status?->value ?? $upload->status ?? 'unknown');
                    if ($status === 'processed') continue;

                    // BD-required upload is pending/failed while run is marked success → stale
                    $uploadTs = $upload->updated_at ?? $upload->created_at;
                    $staleUploads[]    = $code;
                    $staleUploadInfo[] = [
                        'code'      => $code,
                        'filename'  => $upload->original_name,
                        'status'    => $status,
                        'uploaded'  => optional($uploadTs)->format('d/m/Y H:i'),
                        'last_run'  => optional($dbRun->finished_at)->format('d/m/Y H:i'),
                        'reason'    => 'Upload en estado "' . $status . '" aunque el último DB_UPDATE_RUN completó exitosamente. Vuelve a ejecutar Cargar registros.',
                    ];
                }
            }
        }

        $summaryValid    = in_array($summary?->status, ['database_updated', 'generated'], true)
                           && !$summary?->invalidated_at
                           && empty($staleUploads);   // stale uploads invalidate BD state
        $databaseUpdated = $summaryValid || ($compoundPeriod && empty($missingDb) && empty($failedDb));

        $radiographyReady = ($summary?->status === 'generated') && !$summary?->invalidated_at && empty($staleUploads);
        $runStatus        = $run?->status;
        $running          = in_array($runStatus, ['queued', 'running'], true);
        $dbRunStatus      = $dbRun?->status;
        $dbRunning        = in_array($dbRunStatus, ['queued', 'running'], true);

        $dbElapsedSeconds = null;
        $dbStuckWarning   = false;
        $dbJobOrphaned    = false;
        if ($dbRun) {
            if ($dbRunning) {
                $ref = $dbRunStatus === 'queued'
                    ? ($dbRun->queued_at ?? $dbRun->created_at)
                    : ($dbRun->started_at ?? $dbRun->queued_at ?? $dbRun->created_at);
                $dbElapsedSeconds = $ref ? max(0, (int) now()->diffInSeconds($ref)) : null;
                $dbStuckWarning   = $dbElapsedSeconds !== null && (
                    ($dbRunStatus === 'queued' && $dbElapsedSeconds >= 300) ||
                    ($dbRunStatus !== 'queued' && $dbElapsedSeconds >= 1800)
                );
                if ($dbRunStatus === 'queued') {
                    $dbJobOrphaned = !$this->jobExistsForRun($dbRun->id);
                }
            } elseif ($dbRun->started_at && $dbRun->finished_at) {
                $dbElapsedSeconds = max(0, (int) $dbRun->started_at->diffInSeconds($dbRun->finished_at));
            }
        }

        $blockingReasons = [];
        if (!empty($missingDb)) {
            $blockingReasons[] = 'Faltan archivos de BD obligatorios: ' . implode(', ', $missingDb) . '.';
        }
        if (!empty($failedDb)) {
            $blockingReasons[] = 'Fuentes de BD tienen error de procesamiento.';
        }
        if ($dbRunning) {
            $blockingReasons[] = 'La actualización de base de datos está en proceso.';
        }
        if (!empty($staleUploads)) {
            $names = implode(', ', array_map(
                fn ($s) => $s['code'] . ' (' . $s['filename'] . ', subido ' . $s['uploaded'] . ')',
                $staleUploadInfo
            ));
            $blockingReasons[] = "Se reemplazaron archivos de BD después de la última carga "
                . "(última carga: " . optional($dbRun?->finished_at)->format('d/m/Y H:i') . "). "
                . "Ejecuta nuevamente Cargar registros. Archivos: {$names}.";
        }
        if (!$databaseUpdated) {
            $blockingReasons[] = 'Primero actualiza la BD (ejecuta Cargar registros).';
        }
        if ($pendingCritical > 0) {
            $blockingReasons[] = 'Hay incidencias críticas pendientes.';
        }
        if (!empty($missingRadiography)) {
            $blockingReasons[] = 'Faltan fuentes para generar la Radiografía: ' . implode(', ', $missingRadiography) . '.';
        }
        if (!empty($unprocessedRadiography)) {
            $details = implode('; ', collect($unprocessedRadiography)->map(function ($code) use ($uploads) {
                $u = $uploads->first(fn ($item) => ($item->dataSource?->code ?? '') === $code);
                $status   = $u ? (string) ($u->status?->value ?? $u->status ?? 'desconocido') : 'no subido';
                $filename = $u?->original_name ?? 'sin archivo';
                return "{$code} — {$filename} [{$status}]";
            })->all());
            $blockingReasons[] = "Fuentes sin procesar (todas deben estar en estado 'procesado' para generar): {$details}";
        }
        if ($running) {
            $blockingReasons[] = 'La Radiografía está en proceso.';
        }

        $previewSummary = null;
        if ($radiographyReady && $summary) {
            $gm = $summary->global_metrics ?? [];

            $needsRecompute = (($gm['colocacion_total'] ?? 0) == 0 && ($gm['valor_cartera_total'] ?? 0) == 0)
                || ($gm['recuperacion_total'] ?? 0) == 0;

            if ($needsRecompute) {
                $period = \App\Models\Period::find($summary->period_id);
                if ($period) {
                    $allPeriodsLocal = \App\Models\Period::all();
                    $weeklyIdsLocal  = $period->resolveBaseWeeklyIds($allPeriodsLocal);
                    if (empty($weeklyIdsLocal)) {
                        $weeklyIdsLocal = [$period->id];
                    }
                    $dataIdsLocal = array_values(array_unique(array_merge($weeklyIdsLocal, [$period->id])));

                    if (($gm['colocacion_total'] ?? 0) == 0) {
                        $gm['colocacion_total'] = (float) DB::table('fact_placements')->whereIn('period_id', $dataIdsLocal)->sum('amount');
                    }
                    if (($gm['recuperacion_total'] ?? 0) == 0) {
                        $gm['recuperacion_total'] = (float) DB::table('fact_recoveries')->whereIn('period_id', $dataIdsLocal)->sum('total_amount');
                    }
                    if (($gm['valor_cartera_total'] ?? 0) == 0) {
                        $ct = (float) DB::table('fact_portfolios')->whereIn('period_id', $dataIdsLocal)->sum('balance');
                        $cv = (float) DB::table('fact_portfolios')->whereIn('period_id', $dataIdsLocal)->where('days_past_due', '>', 0)->sum('balance');
                        $gm['valor_cartera_total']   = $ct;
                        $gm['cartera_vencida_total'] = $cv;
                        $gm['mora_porcentaje']       = $ct > 0 ? round($cv / $ct * 100, 2) : 0;
                    }
                    if (($gm['gasto_total'] ?? 0) == 0) {
                        $gm['gasto_total'] = (float) DB::table('fact_expenses')->whereIn('period_id', $dataIdsLocal)->sum('amount');
                    }
                }
            }

            // Always recompute payroll inline if pagos_total is 0
            if (($gm['pagos_total'] ?? 0) == 0) {
                $periodForPayroll = isset($period) ? $period : \App\Models\Period::find($summary->period_id);
                if ($periodForPayroll) {
                    $mes = DB::table('fact_period_employee_summary')
                        ->where('period_id', $periodForPayroll->id)
                        ->selectRaw('COUNT(*) as cnt, SUM(total_payments) as pagos, SUM(total_bonuses) as bonos, SUM(net_amount) as neto')
                        ->first();
                    $mesPagos = (float)($mes?->pagos ?? 0) + (float)($mes?->bonos ?? 0);
                    if ((int)($mes?->cnt ?? 0) > 0 && $mesPagos > 0) {
                        $gm['total_empleados'] = (int)$mes->cnt;
                        $gm['pagos_total']     = (float)$mes->pagos;
                        $gm['neto_total']      = (float)$mes->neto;
                    } else {
                        // Fallback via NOI
                        if (!isset($dataIdsLocal)) {
                            $allPeriodsLocal2 = \App\Models\Period::all();
                            $wIds = $periodForPayroll->resolveBaseWeeklyIds($allPeriodsLocal2);
                            $dataIdsLocal = empty($wIds) ? [$periodForPayroll->id] : array_values(array_unique(array_merge($wIds, [$periodForPayroll->id])));
                        }
                        $noiPagos = (float) DB::table('fact_noi_movements')
                            ->whereIn('period_id', $dataIdsLocal)
                            ->whereNotNull('employee_id')
                            ->whereRaw("LOWER(COALESCE(concept_type,'')) = 'percepcion'")
                            ->whereRaw("LOWER(COALESCE(concept,'')) NOT LIKE '%bono%'")
                            ->sum('amount');
                        $noiComisiones = (float) DB::table('fact_noi_movements')
                            ->whereIn('period_id', $dataIdsLocal)
                            ->whereNotNull('employee_id')
                            ->whereRaw("LOWER(COALESCE(concept,'')) LIKE '%comisi%'")
                            ->sum('amount');
                        if ($noiPagos + $noiComisiones > 0) {
                            $gm['pagos_total'] = $noiPagos + $noiComisiones;
                            $noiDesc = (float) DB::table('fact_noi_movements')
                                ->whereIn('period_id', $dataIdsLocal)
                                ->whereNotNull('employee_id')
                                ->whereRaw("LOWER(COALESCE(concept_type,'')) IN ('deduccion','descuento')")
                                ->sum('amount');
                            $gm['neto_total'] = $gm['pagos_total'] - $noiDesc;
                        }
                        if (($gm['total_empleados'] ?? 0) == 0) {
                            $gm['total_empleados'] = (int) DB::table('fact_noi_movements')
                                ->whereIn('period_id', $dataIdsLocal)->whereNotNull('employee_id')->distinct('employee_id')->count('employee_id');
                        }
                    }
                }
            }

            $previewSummary = [
                'global_metrics' => $gm,
                'generated_at'   => optional($summary->generated_at)->format('d/m/Y H:i'),
                'version'        => $summary->version,
            ];
        }

        return [
            'database_updated'                => $databaseUpdated,
            'database_invalidated'            => (bool) $summary?->invalidated_at,
            'database_update_run_status'      => $dbRunStatus,
            'database_update_run_log'         => $dbRun?->log ? mb_strimwidth($dbRun->log, 0, 300) : null,
            'database_update_run_error'       => $dbRun?->error_message ? mb_strimwidth($dbRun->error_message, 0, 300) : null,
            'database_update_run_queued_at'   => optional($dbRun?->queued_at ?? $dbRun?->created_at)->format('d/m/Y H:i'),
            'database_update_run_started_at'  => ($dbRunStatus !== 'queued') ? optional($dbRun?->started_at)->format('d/m/Y H:i') : null,
            'database_update_run_finished_at' => optional($dbRun?->finished_at)->format('d/m/Y H:i'),
            'database_update_run_metadata'    => $dbRun?->metadata,
            'database_update_elapsed_seconds' => $dbElapsedSeconds,
            'database_update_stuck_warning'   => $dbStuckWarning,
            'database_update_job_orphaned'    => $dbJobOrphaned,
            'database_update_can_process_now' => !app()->isProduction() && $dbRunStatus === 'queued',
            'pending_critical_incidents_count' => $pendingCritical,
            'missing_database_sources'        => $missingDb,
            'missing_radiography_sources'     => $missingRadiography,
            'unprocessed_radiography_sources' => $unprocessedRadiography,
            'radiography_ready'               => $radiographyReady,
            'radiography_invalidated'         => (bool) $summary?->invalidated_at,
            'radiography_running'             => $running,
            'radiography_run_queued_at'       => optional($run?->queued_at ?? $run?->created_at)->format('d/m/Y H:i'),
            'radiography_run_started_at'      => ($runStatus !== 'queued') ? optional($run?->started_at)->format('d/m/Y H:i') : null,
            'radiography_run_metadata'        => $run?->metadata,
            'radiography_run_error'           => $run?->error_message ? mb_strimwidth($run->error_message, 0, 300) : null,
            'radiography_can_process_now'     => !app()->isProduction() && $runStatus === 'queued',
            'can_update_database'             => empty($missingDb) && empty($failedDb) && !$dbRunning,
            'can_resolve_incidents'           => $databaseUpdated,
            'can_generate_radiography'        => $databaseUpdated && $pendingCritical === 0 && empty($missingRadiography) && empty($unprocessedRadiography) && !$running,
            'can_export_radiography'          => $radiographyReady && empty($missingRadiography) && empty($unprocessedRadiography) && !$running,
            'blocking_reasons'                => array_values(array_unique($blockingReasons)),
            'preview_summary'                 => $previewSummary,
            // Stale-upload state: visible to UI so it can show "archivos reemplazados" warning
            'has_stale_uploads'               => !empty($staleUploads),
            'stale_upload_sources'            => $staleUploads,
            'stale_upload_details'            => $staleUploadInfo,
        ];
    }
}
