<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Collection;

class Period extends Model {

    protected $fillable = [
        'name',
        'code',
        'type',
        'year',
        'month',
        'sequence',
        'start_date',
        'end_date',
        'saldo_inicial_caja',
        'saldo_final_caja',
        'component_period_ids',
        'is_closed',
    ];

    protected $casts = [
        'start_date'           => 'date',
        'end_date'             => 'date',
        'component_period_ids' => 'array',
        'is_closed'            => 'boolean',
    ];

    protected $appends = ['label'];

    // ── Helpers de tipo ────────────────────────────────────────────────

    public function isBase(): bool {
        return $this->type === 'weekly';
    }

    public function isMonthly(): bool {
        return $this->type === 'monthly';
    }

    public function isCompound(): bool {
        return !$this->isBase();
    }

    public function isAutoGenerated(): bool {
        return in_array($this->type, ['bimonthly', 'quarterly', 'semiannual', 'annual'], true);
    }

    public function canReceiveUploads(): bool {
        return $this->type === 'monthly' && !empty($this->component_period_ids);
    }

    // ── Label ──────────────────────────────────────────────────────────

    public function getLabelAttribute(): string {
        if (!empty($this->name)) {
            return $this->name;
        }

        $months = [
            1 => 'Enero', 2 => 'Febrero', 3 => 'Marzo', 4 => 'Abril',
            5 => 'Mayo', 6 => 'Junio', 7 => 'Julio', 8 => 'Agosto',
            9 => 'Septiembre', 10 => 'Octubre', 11 => 'Noviembre', 12 => 'Diciembre',
        ];
        $monthName = $months[(int) $this->month] ?? 'Periodo';

        return match ($this->type) {
            'weekly'    => sprintf('Semana %d %04d-%02d', (int) $this->sequence, (int) $this->year, (int) $this->month),
            'monthly'   => "{$monthName} {$this->year}",
            default     => "{$monthName} {$this->year}",
        };
    }

    // ── Resolución de periodos base (semanas) ─────────────────────────
    // Resuelve recursivamente los IDs de periodos semanales que componen este periodo.
    // Acepta la colección completa de periodos en memoria para evitar N+1.

    public function resolveBaseWeeklyIds(Collection $allPeriods, int $depth = 0): array {
        if ($depth > 5) return [];

        if ($this->isBase()) {
            return [$this->id];
        }

        if (!empty($this->component_period_ids)) {
            $componentIds = collect($this->component_period_ids)->map(fn ($id) => (int) $id)->all();
            $components   = $allPeriods->whereIn('id', $componentIds)->values();
            $weeklyIds    = [];
            foreach ($components as $component) {
                // canReceiveUploads() solo es true para 'monthly': todos los fact_* reales
                // quedan tageados con el period_id del MES, no de sus semanas componentes
                // (las semanas son solo metadata organizativa, nunca reciben cargas). Si no
                // incluimos aquí el ID del mes, un trimestre/bimestre que solo recursa hasta
                // semanas vacías termina sin ningún dataId con datos reales — todo sale en $0.
                if ($component->isMonthly()) {
                    $weeklyIds[] = $component->id;
                }
                foreach ($component->resolveBaseWeeklyIds($allPeriods, $depth + 1) as $wid) {
                    $weeklyIds[] = $wid;
                }
            }
            return array_values(array_unique($weeklyIds));
        }

        // Fallback: date-range overlap con periodos semanales
        $weeklyPeriods = $allPeriods->where('type', 'weekly');
        return $weeklyPeriods->filter(fn ($week) =>
            $week->start_date && $week->end_date &&
            $this->start_date && $this->end_date &&
            $week->start_date->lte($this->end_date) &&
            $week->end_date->gte($this->start_date)
        )->pluck('id')->map(fn ($id) => (int) $id)->values()->all();
    }

    // ── Último mes componente (para métricas de cierre: cartera, mora, préstamo activo) ──
    // Un periodo automático (bimestral/trimestral/semestral/anual) consolida sus meses
    // componentes. Las métricas de FLUJO (recuperación, colocación, gastos, nómina...) se
    // suman entre meses — eso ya sale correcto combinando los dataIds de todos los meses.
    // Pero cartera/mora/préstamo activo son un estado (snapshot de "Saldos Por Cliente" al
    // corte de cada mes), no un flujo: sumarlas entre meses las tri/duplicaría. Deben venir
    // SOLO del último mes componente (el cierre más reciente del periodo).

    public function resolveLastMonthlyComponent(Collection $allPeriods, int $depth = 0): ?self {
        if ($depth > 5) return null;

        if ($this->isMonthly()) {
            return $this;
        }

        if (empty($this->component_period_ids)) {
            return null;
        }

        $componentIds = collect($this->component_period_ids)->map(fn ($id) => (int) $id)->all();
        $components   = $allPeriods->whereIn('id', $componentIds)->values();

        $last = $components->sortBy(fn ($p) => sprintf('%04d%02d%03d', (int) $p->year, (int) $p->month, (int) $p->sequence))->last();

        return $last?->resolveLastMonthlyComponent($allPeriods, $depth + 1);
    }

    // ── Periodo mensual anterior ───────────────────────────────────────
    // Único punto de verdad para "el mes anterior" — usado por rotación/IMSS
    // derivados. Filtra explícitamente type='monthly' (a diferencia de los
    // patrones ad-hoc previos que comparaban ID/fecha sobre TODOS los tipos).

    public function previousMonthly(?Collection $allPeriods = null): ?self {
        if (!$this->isMonthly()) return null;

        $candidates = $allPeriods
            ? $allPeriods->where('type', 'monthly')
            : self::query()->where('type', 'monthly')->get();

        return $candidates
            ->filter(fn ($p) => $p->id !== $this->id
                && ($p->year < $this->year || ($p->year == $this->year && $p->month < $this->month)))
            ->sortByDesc(fn ($p) => sprintf('%04d%02d', $p->year, $p->month))
            ->first();
    }

    // ── Relaciones ─────────────────────────────────────────────────────

    public function reportUploads(): HasMany {
        return $this->hasMany(ReportUpload::class);
    }

    public function processRuns(): HasMany {
        return $this->hasMany(ProcessRun::class);
    }

    public function employeeBranchAssignments(): HasMany {
        return $this->hasMany(EmployeeBranchAssignment::class);
    }

    public function noiMovements(): HasMany {
        return $this->hasMany(NoiMovement::class);
    }

    public function placements(): HasMany {
        return $this->hasMany(Placement::class);
    }

    public function recoveries(): HasMany {
        return $this->hasMany(Recovery::class);
    }

    public function portfolios(): HasMany {
        return $this->hasMany(Portfolio::class);
    }

    public function expenses(): HasMany {
        return $this->hasMany(Expense::class);
    }

    public function monthlyEmployeeSummaries(): HasMany {
        return $this->hasMany(MonthlyEmployeeSummary::class);
    }

    public function radiographyRuns(): HasMany {
        return $this->hasMany(PeriodRadiographyRun::class);
    }

}
